using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HighSpeedDAL.SimpleCrudExample.Data;
using HighSpeedDAL.SimpleCrudExample.Entities;

namespace HighSpeedDAL.SimpleCrudExample;

/// <summary>
/// Demonstrates Guid primary key support - auto-generated and explicit
/// Shows distributed system scenarios where Guid IDs are essential
/// </summary>
public class GuidPrimaryKeyExample
{
    private readonly UserWithGuidIdDal _guidUserDal;
    private readonly OrderWithGuidDal _orderDal;

    public GuidPrimaryKeyExample(
        UserWithGuidIdDal guidUserDal,
        OrderWithGuidDal orderDal)
    {
        _guidUserDal = guidUserDal;
        _orderDal = orderDal;
    }

    public async Task RunAllExamplesAsync()
    {
        Console.WriteLine("===============================================================================");
        Console.WriteLine("              GUID PRIMARY KEY EXAMPLES");
        Console.WriteLine("===============================================================================");
        Console.WriteLine();

        await Example1_AutoGeneratedGuidIdAsync();
        await Example2_ExplicitGuidIdAsync();
        await Example3_BulkOperationsWithGuidsAsync();
        await Example4_DistributedSystemScenarioAsync();

        Console.WriteLine();
        Console.WriteLine("===============================================================================");
        Console.WriteLine("              GUID PRIMARY KEY EXAMPLES COMPLETED");
        Console.WriteLine("===============================================================================");
        Console.WriteLine();
    }

    private async Task Example1_AutoGeneratedGuidIdAsync()
    {
        Console.WriteLine("EXAMPLE 1: Auto-Generated Guid Primary Key");
        Console.WriteLine("-------------------------------------------------------------------------------");
        Console.WriteLine();
        Console.WriteLine("[Table(PrimaryKeyType = PrimaryKeyType.Guid)]");
        Console.WriteLine("public partial class UserWithGuidId");
        Console.WriteLine("{");
        Console.WriteLine("    // Framework auto-generates: public Guid Id { get; set; }");
        Console.WriteLine("    public string Username { get; set; }");
        Console.WriteLine("    // ... other properties");
        Console.WriteLine("}");
        Console.WriteLine();

        // Create user - framework will auto-generate Guid
        var user = new UserWithGuidId
        {
            Username = "alice_guid",
            Email = "alice@distributed.com",
            FirstName = "Alice",
            LastName = "Distributed",
            CreatedAt = DateTime.UtcNow,
            IsActive = true
        };

        Console.WriteLine("Before Insert:");
        Console.WriteLine($"  user.Id = {user.Id} (should be empty)");
        Console.WriteLine();

        // Insert - framework generates Guid before insert
        await _guidUserDal.InsertAsync(user);

        Console.WriteLine("After Insert:");
        Console.WriteLine($"  user.Id = {user.Id}");
        Console.WriteLine($"  Username: {user.Username}");
        Console.WriteLine();

        // Retrieve by Guid
        var retrieved = await _guidUserDal.GetByIdAsync(user.Id);
        Console.WriteLine("Retrieved by Guid:");
        Console.WriteLine($"  Id: {retrieved?.Id}");
        Console.WriteLine($"  Username: {retrieved?.Username}");
        Console.WriteLine($"  Email: {retrieved?.Email}");
        Console.WriteLine();

        Console.WriteLine("[OK] Auto-generated Guid primary key works correctly!");
        Console.WriteLine();
    }

    private async Task Example2_ExplicitGuidIdAsync()
    {
        Console.WriteLine("EXAMPLE 2: Explicit Guid Primary Key");
        Console.WriteLine("-------------------------------------------------------------------------------");
        Console.WriteLine();
        Console.WriteLine("[Table]");
        Console.WriteLine("public class OrderWithGuid");
        Console.WriteLine("{");
        Console.WriteLine("    [PrimaryKey(AutoGenerate = false)]");
        Console.WriteLine("    public Guid Id { get; set; }");
        Console.WriteLine("    public string OrderNumber { get; set; }");
        Console.WriteLine("    // ... other properties");
        Console.WriteLine("}");
        Console.WriteLine();

        // Create order with explicit Guid
        Guid orderId = Guid.NewGuid();
        var order = new OrderWithGuid
        {
            Id = orderId,
            OrderNumber = "ORD-2024-001",
            TotalAmount = 149.99m,
            OrderDate = DateTime.UtcNow,
            CustomerName = "Bob Johnson"
        };

        Console.WriteLine("Explicit Guid:");
        Console.WriteLine($"  orderId = {orderId}");
        Console.WriteLine($"  order.Id = {order.Id}");
        Console.WriteLine();

        await _orderDal.InsertAsync(order);

        Console.WriteLine("After Insert:");
        Console.WriteLine($"  Order stored with explicit Guid: {order.Id}");
        Console.WriteLine();

        // Retrieve by explicit Guid
        var retrieved = await _orderDal.GetByIdAsync(orderId);
        Console.WriteLine("Retrieved by explicit Guid:");
        Console.WriteLine($"  Id: {retrieved?.Id}");
        Console.WriteLine($"  OrderNumber: {retrieved?.OrderNumber}");
        Console.WriteLine($"  TotalAmount: ${retrieved?.TotalAmount:F2}");
        Console.WriteLine($"  CustomerName: {retrieved?.CustomerName}");
        Console.WriteLine();

        Console.WriteLine("[OK] Explicit Guid primary key works correctly!");
        Console.WriteLine();
    }

    private async Task Example3_BulkOperationsWithGuidsAsync()
    {
        Console.WriteLine("EXAMPLE 3: Bulk Operations with Guid Primary Keys");
        Console.WriteLine("-------------------------------------------------------------------------------");
        Console.WriteLine();

        // Create 100 users for bulk insert
        var users = new List<UserWithGuidId>();
        for (int i = 0; i < 100; i++)
        {
            users.Add(new UserWithGuidId
            {
                Username = $"bulk_user_{i}",
                Email = $"bulk{i}@example.com",
                FirstName = $"Bulk{i}",
                LastName = "User",
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            });
        }

        Console.WriteLine($"Bulk inserting {users.Count} users with auto-generated Guids...");
        await _guidUserDal.BulkInsertAsync(users);

        Console.WriteLine($"[OK] All {users.Count} users inserted!");
        Console.WriteLine();

        // Verify all have unique Guids
        var uniqueGuids = users.Select(u => u.Id).Distinct().Count();
        Console.WriteLine($"Uniqueness Check:");
        Console.WriteLine($"  Total users: {users.Count}");
        Console.WriteLine($"  Unique GUIDs: {uniqueGuids}");
        Console.WriteLine($"  All unique: {uniqueGuids == users.Count}");
        Console.WriteLine();

        // Retrieve multiple by Guids
        var sampleGuids = users.Take(10).Select(u => u.Id).ToList();
        var retrieved = await _guidUserDal.GetByIdsAsync(sampleGuids);

        Console.WriteLine($"Retrieved {retrieved.Count()} users by Guid batch:");
        foreach (var user in retrieved.Take(3))
        {
            Console.WriteLine($"  - {user.Username} (Guid: {user.Id})");
        }
        Console.WriteLine($"  ... and {retrieved.Count() - 3} more");
        Console.WriteLine();

        Console.WriteLine("[OK] Bulk operations with Guid primary keys work correctly!");
        Console.WriteLine();
    }

    private async Task Example4_DistributedSystemScenarioAsync()
    {
        Console.WriteLine("EXAMPLE 4: Distributed System Scenario");
        Console.WriteLine("-------------------------------------------------------------------------------");
        Console.WriteLine();
        Console.WriteLine("Simulating 3 independent servers creating users simultaneously:");
        Console.WriteLine("Each server generates its own Guids without coordination.");
        Console.WriteLine();

        // Simulate 3 servers creating users simultaneously
        var server1Users = CreateUsersForServer("Server-1", 10);
        var server2Users = CreateUsersForServer("Server-2", 10);
        var server3Users = CreateUsersForServer("Server-3", 10);

        // Insert from all "servers" (simulated)
        var tasks = new List<Task>
        {
            Task.Run(async () =>
            {
                foreach (var user in server1Users)
                    await _guidUserDal.InsertAsync(user);
            }),
            Task.Run(async () =>
            {
                foreach (var user in server2Users)
                    await _guidUserDal.InsertAsync(user);
            }),
            Task.Run(async () =>
            {
                foreach (var user in server3Users)
                    await _guidUserDal.InsertAsync(user);
            })
        };

        await Task.WhenAll(tasks);

        // Collect all Guids
        var allGuids = new List<Guid>();
        allGuids.AddRange(server1Users.Select(u => u.Id));
        allGuids.AddRange(server2Users.Select(u => u.Id));
        allGuids.AddRange(server3Users.Select(u => u.Id));

        Console.WriteLine("Results:");
        Console.WriteLine($"  Server 1: Created {server1Users.Count} users");
        Console.WriteLine($"  Server 2: Created {server2Users.Count} users");
        Console.WriteLine($"  Server 3: Created {server3Users.Count} users");
        Console.WriteLine($"  Total: {allGuids.Count} users");
        Console.WriteLine();

        var uniqueGuids = allGuids.Distinct().Count();
        Console.WriteLine($"Collision Check:");
        Console.WriteLine($"  Total GUIDs: {allGuids.Count}");
        Console.WriteLine($"  Unique GUIDs: {uniqueGuids}");
        Console.WriteLine($"  Collisions: {allGuids.Count - uniqueGuids}");
        Console.WriteLine();

        if (uniqueGuids == allGuids.Count)
        {
            Console.WriteLine("[OK] No Guid collisions! Distributed system scenario successful!");
        }
        else
        {
            Console.WriteLine("[WARNING] Guid collisions detected (should never happen)!");
        }

        Console.WriteLine();

        // Show sample from each server
        Console.WriteLine("Sample users from each server:");
        var sample1 = server1Users.First();
        var sample2 = server2Users.First();
        var sample3 = server3Users.First();

        Console.WriteLine($"  Server 1: {sample1.Username} (Guid: {sample1.Id})");
        Console.WriteLine($"  Server 2: {sample2.Username} (Guid: {sample2.Id})");
        Console.WriteLine($"  Server 3: {sample3.Username} (Guid: {sample3.Id})");
        Console.WriteLine();
    }

    private List<UserWithGuidId> CreateUsersForServer(string serverName, int count)
    {
        var users = new List<UserWithGuidId>();
        for (int i = 0; i < count; i++)
        {
            users.Add(new UserWithGuidId
            {
                Username = $"{serverName.ToLower()}_user_{i}",
                Email = $"{serverName.ToLower()}_{i}@distributed.com",
                FirstName = serverName,
                LastName = $"User{i}",
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            });
        }
        return users;
    }
}
