using HighSpeedDAL.Core.Attributes;

namespace ShowcaseExample.Entities;

/// <summary>
/// Product entity demonstrating auto-audit and caching features.
/// Framework automatically generates Id, audit properties, and ShallowClone()/DeepClone() methods.
/// </summary>
[DalEntity]
[Table("Products")]
[Cache(CacheStrategy.TwoLayer, ExpirationSeconds = 300)]
[AutoAudit]
public partial class Product
{
    // Id property auto-generated by source generator (int Id { get; set; })
    
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public decimal Price { get; set; }
    public int StockQuantity { get; set; }
    public string Category { get; set; } = string.Empty;
    public bool IsActive { get; set; } = true;

    // Audit properties auto-generated by source generator:
    // - CreatedBy, CreatedDate, ModifiedBy, ModifiedDate
}

/// <summary>
/// Order entity with soft delete support.
/// Demonstrates staging table for high-write scenarios.
/// </summary>
[DalEntity]
[Table("Orders")]
[StagingTable(SyncIntervalSeconds = 30, BatchSize = 1000)]
[AutoAudit]
[SoftDelete]
public partial class Order
{
    // Auto-generated: Id, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate
    // Auto-generated: IsDeleted, DeletedBy, DeletedDate

    public string OrderNumber { get; set; } = string.Empty;
    public int CustomerId { get; set; }
    public decimal TotalAmount { get; set; }
    public string Status { get; set; } = "Pending";
    public DateTime OrderDate { get; set; } = DateTime.UtcNow;
    public DateTime? ShippedDate { get; set; }
}

/// <summary>
/// Customer entity demonstrating memory-cache strategy.
/// Reference data that changes infrequently.
/// </summary>
[DalEntity]
[Table("Customers")]
[Cache(CacheStrategy.Memory, ExpirationSeconds = 600)]
[AutoAudit]
public partial class Customer
{
    // Auto-generated: Id, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate

    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string? Phone { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? Country { get; set; }
    public bool IsActive { get; set; } = true;
}

/// <summary>
/// OrderItem entity demonstrating in-memory table for fast access.
/// High-frequency reads with occasional writes.
/// </summary>
[DalEntity]
[Table("OrderItems")]
[InMemoryTable(FlushIntervalSeconds = 60, MaxRowCount = 100000)]
public partial class OrderItem
{
    // Auto-generated: Id

    public int OrderId { get; set; }
    public int ProductId { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal Discount { get; set; }
    public decimal TotalPrice => Quantity * UnitPrice * (1 - Discount);
}

/// <summary>
/// ActivityLog entity demonstrating memory-mapped file for ultra-high throughput.
/// Write-heavy logging scenario with millions of entries.
/// </summary>
[DalEntity]
[Table("ActivityLogs")]
[MemoryMappedTable(FileName = "ActivityLogs", SizeMB = 100, FlushIntervalSeconds = 10)]
public partial class ActivityLog
{
    // Auto-generated: Id

    public string UserId { get; set; } = string.Empty;
    public string Action { get; set; } = string.Empty;
    public string? Details { get; set; }
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    public string IpAddress { get; set; } = string.Empty;
    public int DurationMs { get; set; }
}

/// <summary>
/// ProductCategory reference table pre-loaded into memory.
/// Static lookup data accessed frequently.
/// </summary>
[DalEntity]
[Table("ProductCategories")]
[ReferenceTable(LoadOnStartup = true)]
public partial class ProductCategory
{
    // Auto-generated: Id

    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public bool IsActive { get; set; } = true;
}
