using System;
using HighSpeedDAL.Core.Attributes;
using MessagePack;

namespace ExpressRecipe.ProductService.Entities;

[DalEntity]
[Table("Ingredient", PrimaryKeyType = PrimaryKeyType.Guid)]
[Cache(CacheStrategy.TwoLayer, MaxSize = 20000, ExpirationSeconds = 1800)]
[InMemoryTable(FlushIntervalSeconds = 30, MaxRowCount = 100000)]
[AutoAudit]
[SoftDelete]
[MessagePackObject]
public partial class IngredientEntity
{
    [Key(0)]
    [PrimaryKey]
    public Guid Id { get; set; }

    [Key(1)]
    [Index(IsUnique = true)]
    public string Name { get; set; } = string.Empty;

    [Key(2)]
    public string? AlternativeNames { get; set; }

    [Key(3)]
    public string? Description { get; set; }

    [Key(4)]
    [Index]
    public string? Category { get; set; }

    [Key(5)]
    public bool IsCommonAllergen { get; set; } = false;

    // Note: The following properties are auto-generated by HighSpeedDAL framework
    // due to [AutoAudit] and [SoftDelete] attributes on the class:
    // - CreatedDate, CreatedBy (from [AutoAudit])
    // - ModifiedDate, ModifiedBy (from [AutoAudit])
    // - IsDeleted, DeletedDate, DeletedBy (from [SoftDelete])
}
