using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Logging;
using HighSpeedDAL.Core.DataManagement;

namespace ExpressRecipe.ProductService.Entities
{
    /// <summary>
    /// Partial extension to ProductStagingEntityDal with optimized bulk operations
    /// </summary>
    public sealed partial class ProductStagingEntityDal
    {
        // Removed GetByExternalIdAsync, GetByBarcodeAsync, GetByProcessingStatusAsync
        // These are now generated by HighSpeedDAL source generator via [NamedQuery] attributes
        // to ensure proper InMemoryTable integration.

        /// <summary>
        /// Bulk updates processing status for multiple staging products
        /// Uses DAL UpdateAsync to ensure InMemoryTable is updated and changes are flushed via standard pipeline
        /// </summary>
        public async Task<int> BulkUpdateProcessingStatusAsync(IEnumerable<Guid> ids, string status, string? error, CancellationToken cancellationToken = default)
        {
            List<Guid> idList = new List<Guid>(ids);
            if (idList.Count == 0)
            {
                return 0;
            }

            Logger.LogInformation("Bulk updating {Count} product staging statuses to '{Status}'", idList.Count, status);

            // Fetch entities from DAL (checks memory first)
            List<ProductStagingEntity> entities = await GetByIdsAsync(idList);

            // Update fields in memory
            DateTime now = DateTime.UtcNow;
            
            // Process in parallel batches to maximize throughput
            const int BATCH_SIZE = 200;
            int totalUpdated = 0;

            for (int i = 0; i < entities.Count; i += BATCH_SIZE)
            {
                List<ProductStagingEntity> batch = entities.Skip(i).Take(BATCH_SIZE).ToList();
                
                foreach (ProductStagingEntity entity in batch)
                {
                    entity.ProcessingStatus = status;
                    entity.ProcessingAttempts++;
                    entity.ProcessingError = error;
                    if (status == "Completed")
                    {
                        entity.ProcessedAt = now;
                    }
                }

                // UpdateAsync updates the InMemoryTable row state and queues it for flushing.
                // It is very fast (microsecond latency).
                List<Task<ProductStagingEntity>> updateTasks = batch
                    .Select(e => UpdateAsync(e, "System", cancellationToken))
                    .ToList();
                
                await Task.WhenAll(updateTasks);
                totalUpdated += batch.Count;
            }

            return totalUpdated;
        }

        /// <summary>
        /// Optimized bulk insert to temp table using SqlBulkCopy for table swap flush
        /// </summary>
        public async Task<int> BulkInsertToTempTableAsync(List<ProductStagingEntity> entities, string tempTableName)
        {
            if (entities == null || entities.Count == 0)
            {
                return 0;
            }

            Logger.LogInformation("Bulk inserting {Count} entities to temp table '{TempTable}'", entities.Count, tempTableName);

            const int BATCH_SIZE = 1000;
            int totalInserted = 0;

            try
            {
                for (int i = 0; i < entities.Count; i += BATCH_SIZE)
                {
                    List<ProductStagingEntity> batch = entities.Skip(i).Take(BATCH_SIZE).ToList();

                    using SqlConnection connection = new SqlConnection(Connection.ConnectionString);
                    await connection.OpenAsync();

                    using SqlBulkCopy bulkCopy = new SqlBulkCopy(connection)
                    {
                        DestinationTableName = $"[{tempTableName}]",
                        BatchSize = BATCH_SIZE,
                        BulkCopyTimeout = 300
                    };

                    DataTable dataTable = CreateProductStagingDataTable(batch);
                    AddBulkCopyColumnMappings(bulkCopy);

                    await bulkCopy.WriteToServerAsync(dataTable);
                    totalInserted += batch.Count;
                }

                return totalInserted;
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Failed to bulk insert to temp table");
                throw;
            }
        }

        private DataTable CreateProductStagingDataTable(List<ProductStagingEntity> entities)
        {
            DataTable dataTable = new DataTable("ProductStaging");

            dataTable.Columns.Add("Id", typeof(Guid));
            dataTable.Columns.Add("ExternalId", typeof(string));
            dataTable.Columns.Add("Barcode", typeof(string));
            dataTable.Columns.Add("ProductName", typeof(string));
            dataTable.Columns.Add("GenericName", typeof(string));
            dataTable.Columns.Add("Brands", typeof(string));
            dataTable.Columns.Add("IngredientsText", typeof(string));
            dataTable.Columns.Add("IngredientsTextEn", typeof(string));
            dataTable.Columns.Add("Allergens", typeof(string));
            dataTable.Columns.Add("AllergensHierarchy", typeof(string));
            dataTable.Columns.Add("Categories", typeof(string));
            dataTable.Columns.Add("CategoriesHierarchy", typeof(string));
            dataTable.Columns.Add("NutritionData", typeof(string));
            dataTable.Columns.Add("ImageUrl", typeof(string));
            dataTable.Columns.Add("ImageSmallUrl", typeof(string));
            dataTable.Columns.Add("Lang", typeof(string));
            dataTable.Columns.Add("Countries", typeof(string));
            dataTable.Columns.Add("NutriScore", typeof(string));
            dataTable.Columns.Add("NovaGroup", typeof(int?));
            dataTable.Columns.Add("EcoScore", typeof(string));
            dataTable.Columns.Add("RawJson", typeof(string));
            dataTable.Columns.Add("ProcessingStatus", typeof(string));
            dataTable.Columns.Add("ProcessingAttempts", typeof(int));
            dataTable.Columns.Add("ProcessingError", typeof(string));
            dataTable.Columns.Add("ProcessedAt", typeof(DateTime?));
            
            // Use standardized extensions for Audit and Soft Delete columns
            dataTable.AddAuditColumns();
            dataTable.AddSoftDeleteColumns();

            foreach (ProductStagingEntity entity in entities)
            {
                DataRow row = dataTable.NewRow();
                row["Id"] = entity.Id;
                row["ExternalId"] = (object?)entity.ExternalId ?? DBNull.Value;
                row["Barcode"] = (object?)entity.Barcode ?? DBNull.Value;
                row["ProductName"] = (object?)entity.ProductName ?? DBNull.Value;
                row["GenericName"] = (object?)entity.GenericName ?? DBNull.Value;
                row["Brands"] = (object?)entity.Brands ?? DBNull.Value;
                row["IngredientsText"] = (object?)entity.IngredientsText ?? DBNull.Value;
                row["IngredientsTextEn"] = (object?)entity.IngredientsTextEn ?? DBNull.Value;
                row["Allergens"] = (object?)entity.Allergens ?? DBNull.Value;
                row["AllergensHierarchy"] = (object?)entity.AllergensHierarchy ?? DBNull.Value;
                row["Categories"] = (object?)entity.Categories ?? DBNull.Value;
                row["CategoriesHierarchy"] = (object?)entity.CategoriesHierarchy ?? DBNull.Value;
                row["NutritionData"] = (object?)entity.NutritionData ?? DBNull.Value;
                row["ImageUrl"] = (object?)entity.ImageUrl ?? DBNull.Value;
                row["ImageSmallUrl"] = (object?)entity.ImageSmallUrl ?? DBNull.Value;
                row["Lang"] = (object?)entity.Lang ?? DBNull.Value;
                row["Countries"] = (object?)entity.Countries ?? DBNull.Value;
                row["NutriScore"] = (object?)entity.NutriScore ?? DBNull.Value;
                row["NovaGroup"] = entity.NovaGroup.HasValue ? (object)entity.NovaGroup.Value : DBNull.Value;
                row["EcoScore"] = (object?)entity.EcoScore ?? DBNull.Value;
                row["RawJson"] = (object?)entity.RawJson ?? DBNull.Value;
                row["ProcessingStatus"] = (object?)entity.ProcessingStatus ?? DBNull.Value;
                row["ProcessingAttempts"] = entity.ProcessingAttempts;
                row["ProcessingError"] = (object?)entity.ProcessingError ?? DBNull.Value;
                row["ProcessedAt"] = (object?)entity.ProcessedAt ?? DBNull.Value;
                
                // Use standardized extensions to map Audit and Soft Delete properties
                row.MapAuditColumns(entity);
                row.MapSoftDeleteColumns(entity);

                dataTable.Rows.Add(row);
            }

            return dataTable;
        }

        private void AddBulkCopyColumnMappings(SqlBulkCopy bulkCopy)
        {
            // Map Entity Property/DataTable Column -> SQL Column
            bulkCopy.ColumnMappings.Add("Id", "Id");
            bulkCopy.ColumnMappings.Add("ExternalId", "ExternalId");
            bulkCopy.ColumnMappings.Add("Barcode", "Barcode");
            bulkCopy.ColumnMappings.Add("ProductName", "ProductName");
            bulkCopy.ColumnMappings.Add("GenericName", "GenericName");
            bulkCopy.ColumnMappings.Add("Brands", "Brands");
            bulkCopy.ColumnMappings.Add("IngredientsText", "IngredientsText");
            bulkCopy.ColumnMappings.Add("IngredientsTextEn", "IngredientsTextEn");
            bulkCopy.ColumnMappings.Add("Allergens", "Allergens");
            bulkCopy.ColumnMappings.Add("AllergensHierarchy", "AllergensHierarchy");
            bulkCopy.ColumnMappings.Add("Categories", "Categories");
            bulkCopy.ColumnMappings.Add("CategoriesHierarchy", "CategoriesHierarchy");
            bulkCopy.ColumnMappings.Add("NutritionData", "NutritionData");
            bulkCopy.ColumnMappings.Add("ImageUrl", "ImageUrl");
            bulkCopy.ColumnMappings.Add("ImageSmallUrl", "ImageSmallUrl");
            bulkCopy.ColumnMappings.Add("Lang", "Lang");
            bulkCopy.ColumnMappings.Add("Countries", "Countries");
            bulkCopy.ColumnMappings.Add("NutriScore", "NutriScore");
            bulkCopy.ColumnMappings.Add("NovaGroup", "NovaGroup");
            bulkCopy.ColumnMappings.Add("EcoScore", "EcoScore");
            bulkCopy.ColumnMappings.Add("RawJson", "RawJson");
            bulkCopy.ColumnMappings.Add("ProcessingStatus", "ProcessingStatus");
            bulkCopy.ColumnMappings.Add("ProcessingAttempts", "ProcessingAttempts");
            bulkCopy.ColumnMappings.Add("ProcessingError", "ProcessingError");
            bulkCopy.ColumnMappings.Add("ProcessedAt", "ProcessedAt");
            
            // Map Audit Columns
            bulkCopy.ColumnMappings.Add("CreatedDate", "CreatedDate");
            bulkCopy.ColumnMappings.Add("CreatedBy", "CreatedBy");
            bulkCopy.ColumnMappings.Add("ModifiedDate", "ModifiedDate");
            bulkCopy.ColumnMappings.Add("ModifiedBy", "ModifiedBy");
            
            // Map Soft Delete Columns
            bulkCopy.ColumnMappings.Add("IsDeleted", "IsDeleted");
            bulkCopy.ColumnMappings.Add("DeletedDate", "DeletedDate");
            bulkCopy.ColumnMappings.Add("DeletedBy", "DeletedBy");
        }
    }
}