using System;
using HighSpeedDAL.Core.Attributes;
using MessagePack;

namespace ExpressRecipe.ProductService.Entities
{
    /// <summary>
    /// Represents the association between a Product and an Ingredient.
    /// </summary>
    [DalEntity]
    [Table("ProductIngredient", PrimaryKeyType = PrimaryKeyType.Guid)]
    [AutoAudit]
    [SoftDelete]
    // Named queries for efficient lookups
    [NamedQuery("ByProductId", nameof(ProductId))]
    [NamedQuery("ByIngredientId", nameof(IngredientId))]
    [MessagePackObject]
    public partial class ProductIngredientEntity
    {
        [Key(0)]
        [PrimaryKey]
        public Guid Id { get; set; }

        [Key(1)]
        [Index]
        public Guid ProductId { get; set; }

        [Key(2)]
        [Index]
        public Guid IngredientId { get; set; }

        [Key(3)]
        public int OrderIndex { get; set; }

        [Key(4)]
        public string? Quantity { get; set; }

        [Key(5)]
        public string? Notes { get; set; }

        // Note: The following properties are auto-generated by HighSpeedDAL framework
        // due to [AutoAudit] and [SoftDelete] attributes on the class:
        // - CreatedDate, CreatedBy
        // - ModifiedDate, ModifiedBy
        // - IsDeleted, DeletedDate, DeletedBy
    }
}
