using System.ComponentModel.DataAnnotations;

using HighSpeedDAL.Core.Attributes;

namespace HighSpeedDAL.Example.Entities;

/// <summary>
/// Simple product entity with auto-generated CRUD operations
/// </summary>
[DalEntity(AutoCreate = true, AutoMigrate = true)]
[Cache(CacheStrategy.TwoLayer, MaxSize = 1000, ExpirationSeconds = 300)]
[AutoAudit]
[SoftDelete]
public partial class Product
{
    // Primary key property (auto-increment)
    public int Id { get; set; }

    [MaxLength(200)]
    [Index]
    public string Name { get; set; } = string.Empty;

    [MaxLength(1000)]
    public string Description { get; set; } = string.Empty;

    [Column(TypeName = "decimal(18,2)")]
    public decimal Price { get; set; }

    public int StockQuantity { get; set; }

                [Index]
                public int CategoryId { get; set; }

                public bool IsActive { get; set; } = true;

                // NOTE: Audit and soft-delete properties (CreatedBy, CreatedDate, ModifiedBy, ModifiedDate,
                // IsDeleted, DeletedDate, DeletedBy) are auto-generated by the framework for partial classes
                // with [AutoAudit] and [SoftDelete] attributes. No need to define them explicitly.
            }

/// <summary>
/// Category reference table with pre-loaded data
/// </summary>
[DalEntity(AutoCreate = true)]
[ReferenceTable]
[Cache(CacheStrategy.Memory, MaxSize = 100)]
public partial class Category
{
    [Identity]
    public int Id { get; set; }

    [MaxLength(100)]
    [Index(IsUnique = true)]
    public string Name { get; set; } = string.Empty;

    [MaxLength(500)]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Static method to provide reference data
    /// Called automatically on startup by the framework
    /// </summary>
    public static Category[] GetReferenceData()
    {
        return new Category[]
        {
            new Category { Id = 1, Name = "Electronics", Description = "Electronic devices and accessories" },
            new Category { Id = 2, Name = "Clothing", Description = "Apparel and fashion items" },
            new Category { Id = 3, Name = "Books", Description = "Books and publications" },
            new Category { Id = 4, Name = "Home & Garden", Description = "Home improvement and garden supplies" },
            new Category { Id = 5, Name = "Sports", Description = "Sports equipment and gear" }
        };
    }
}

/// <summary>
/// Customer entity with full auditing and row versioning
/// </summary>
[DalEntity(AutoCreate = true, AutoMigrate = true)]
[Cache(CacheStrategy.TwoLayer, MaxSize = 5000, ExpirationSeconds = 300)]
[AutoAudit]
[SoftDelete]
public partial class Customer
{
    // Primary key property (auto-increment)
    public int Id { get; set; }

    [MaxLength(100)]
    public string FirstName { get; set; } = string.Empty;

    [MaxLength(100)]
    public string LastName { get; set; } = string.Empty;

    [MaxLength(255)]
    [Index(IsUnique = true)]
    public string Email { get; set; } = string.Empty;

    [MaxLength(20)]
    public string? Phone { get; set; }

    [MaxLength(500)]
    public string? Address { get; set; }

    [MaxLength(100)]
    public string? City { get; set; }

    [MaxLength(50)]
    public string? State { get; set; }

    [MaxLength(20)]
    public string? PostalCode { get; set; }

                public DateTime? DateOfBirth { get; set; }

                public bool IsActive { get; set; } = true;

                // NOTE: Audit and soft-delete properties (CreatedBy, CreatedDate, ModifiedBy, ModifiedDate,
                // IsDeleted, DeletedDate, DeletedBy) are auto-generated by the framework for partial classes
                // with [AutoAudit] and [SoftDelete] attributes. No need to define them explicitly.
            }

/// <summary>
/// Order entity with staging table for high-write scenarios
/// </summary>
[DalEntity(AutoCreate = true, AutoMigrate = true)]
[StagingTable(MergeIntervalSeconds = 30)]
[AutoAudit]
public partial class Order
{
    public int Id { get; set; }

    [Index]
    public int CustomerId { get; set; }

    [MaxLength(50)]
    [Index]
    public string OrderNumber { get; set; } = string.Empty;

    public DateTime OrderDate { get; set; } = DateTime.UtcNow;

    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalAmount { get; set; }

    [MaxLength(50)]
    public string Status { get; set; } = "Pending";

                [MaxLength(500)]
                public string? ShippingAddress { get; set; }

                [MaxLength(500)]
                public string? Notes { get; set; }

                // NOTE: Audit properties (CreatedBy, CreatedDate, ModifiedBy, ModifiedDate) are auto-generated
                // by the framework for partial classes with [AutoAudit] attribute. No need to define them explicitly.
            }

/// <summary>
/// Order item (line item in an order)
/// </summary>
[DalEntity(AutoCreate = true, AutoMigrate = true)]
[AutoAudit]
public partial class OrderItem
{
    public int Id { get; set; }

    [Index]
    public int OrderId { get; set; }

    [Index]
    public int ProductId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(18,2)")]
    public decimal UnitPrice { get; set; }

                [Column(TypeName = "decimal(18,2)")]
                public decimal LineTotal { get; set; }

                [MaxLength(200)]
                public string? Notes { get; set; }

                // NOTE: Audit properties (CreatedBy, CreatedDate, ModifiedBy, ModifiedDate) are auto-generated
                // by the framework for partial classes with [AutoAudit] attribute. No need to define them explicitly.
            }

/// <summary>
/// Simple inventory tracking entity
/// Demonstrates minimal configuration - just the attribute and properties
/// </summary>
[DalEntity]
public partial class InventoryTransaction
{
    public int Id { get; set; }
    public int ProductId { get; set; }
    public string TransactionType { get; set; } = string.Empty; // "IN" or "OUT"
    public int Quantity { get; set; }
    public DateTime TransactionDate { get; set; } = DateTime.UtcNow;
    public string? Reference { get; set; }
    public string? Notes { get; set; }
}
