using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluentAssertions;
using HighSpeedDAL.Core.Attributes;
using HighSpeedDAL.SimpleCrudExample.Data;
using HighSpeedDAL.SimpleCrudExample.Entities;
using Xunit;

namespace HighSpeedDAL.Core.Tests;

/// <summary>
/// Tests for Guid primary key support (auto-generated and explicit)
/// </summary>
public class GuidPrimaryKeyTests : IDisposable
{
    private readonly UserWithGuidIdDal _guidUserDal;
    private readonly OrderWithGuidDal _orderDal;
    private readonly UserDatabaseConnection _connection;

    public GuidPrimaryKeyTests()
    {
        string connectionString = "Data Source=:memory:";
        _connection = new UserDatabaseConnection(connectionString);
        _guidUserDal = new UserWithGuidIdDal(_connection);
        _orderDal = new OrderWithGuidDal(_connection);
    }

    [Fact]
    public async Task InsertAsync_WithAutoGeneratedGuidId_ShouldGenerateGuidAndInsert()
    {
        // Arrange
        var user = new UserWithGuidId
        {
            Username = "guiduser1",
            Email = "guid1@example.com",
            FirstName = "Guid",
            LastName = "User",
            CreatedAt = DateTime.UtcNow,
            IsActive = true
        };

        // Act - Insert (framework should auto-set Id to new Guid)
        await _guidUserDal.InsertAsync(user);

        // Assert
        user.Id.Should().NotBe(Guid.Empty, "Framework should generate a new Guid for Id");

        // Verify can retrieve by generated Id
        var retrieved = await _guidUserDal.GetByIdAsync(user.Id);
        retrieved.Should().NotBeNull();
        retrieved!.Username.Should().Be("guiduser1");
        retrieved.Id.Should().Be(user.Id);
    }

    [Fact]
    public async Task InsertAsync_WithExplicitGuidId_ShouldUseProvidedGuid()
    {
        // Arrange
        Guid customGuid = Guid.NewGuid();
        var order = new OrderWithGuid
        {
            Id = customGuid,
            OrderNumber = "ORD-001",
            TotalAmount = 99.99m,
            OrderDate = DateTime.UtcNow,
            CustomerName = "John Doe"
        };

        // Act
        await _orderDal.InsertAsync(order);

        // Assert
        order.Id.Should().Be(customGuid, "Explicit Guid should be preserved");

        // Verify can retrieve by provided Guid
        var retrieved = await _orderDal.GetByIdAsync(customGuid);
        retrieved.Should().NotBeNull();
        retrieved!.OrderNumber.Should().Be("ORD-001");
        retrieved.Id.Should().Be(customGuid);
    }

    [Fact]
    public async Task GetAllAsync_WithGuidIds_ShouldRetrieveAllRecords()
    {
        // Arrange
        var users = new List<UserWithGuidId>
        {
            new UserWithGuidId
            {
                Username = "user1",
                Email = "user1@example.com",
                FirstName = "User",
                LastName = "One",
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            },
            new UserWithGuidId
            {
                Username = "user2",
                Email = "user2@example.com",
                FirstName = "User",
                LastName = "Two",
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            }
        };

        // Act
        foreach (var user in users)
        {
            await _guidUserDal.InsertAsync(user);
        }

        var allUsers = await _guidUserDal.GetAllAsync();

        // Assert
        allUsers.Should().HaveCountGreaterOrEqualTo(2);
        users.All(u => u.Id != Guid.Empty).Should().BeTrue("All users should have generated Guids");
        users.Select(u => u.Id).Distinct().Should().HaveCount(users.Count, "All Guids should be unique");
    }

    [Fact]
    public async Task UpdateAsync_WithGuidId_ShouldUpdateRecord()
    {
        // Arrange
        var user = new UserWithGuidId
        {
            Username = "updatetest",
            Email = "update@example.com",
            FirstName = "Update",
            LastName = "Test",
            CreatedAt = DateTime.UtcNow,
            IsActive = true
        };
        await _guidUserDal.InsertAsync(user);
        Guid userId = user.Id;

        // Act
        user.Email = "updated@example.com";
        user.IsActive = false;
        await _guidUserDal.UpdateAsync(user);

        // Assert
        var retrieved = await _guidUserDal.GetByIdAsync(userId);
        retrieved.Should().NotBeNull();
        retrieved!.Email.Should().Be("updated@example.com");
        retrieved.IsActive.Should().BeFalse();
        retrieved.Id.Should().Be(userId, "Id should remain unchanged");
    }

    [Fact]
    public async Task DeleteAsync_WithGuidId_ShouldRemoveRecord()
    {
        // Arrange
        var user = new UserWithGuidId
        {
            Username = "deletetest",
            Email = "delete@example.com",
            FirstName = "Delete",
            LastName = "Test",
            CreatedAt = DateTime.UtcNow,
            IsActive = true
        };
        await _guidUserDal.InsertAsync(user);
        Guid userId = user.Id;

        // Verify user exists
        var beforeDelete = await _guidUserDal.GetByIdAsync(userId);
        beforeDelete.Should().NotBeNull();

        // Act
        await _guidUserDal.DeleteAsync(userId);

        // Assert
        var afterDelete = await _guidUserDal.GetByIdAsync(userId);
        afterDelete.Should().BeNull("User should be deleted");
    }

    [Fact]
    public async Task BulkInsertAsync_WithGuidIds_ShouldInsertAllRecords()
    {
        // Arrange
        var users = new List<UserWithGuidId>();
        for (int i = 0; i < 100; i++)
        {
            users.Add(new UserWithGuidId
            {
                Username = $"bulkuser{i}",
                Email = $"bulk{i}@example.com",
                FirstName = $"Bulk{i}",
                LastName = "User",
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            });
        }

        // Act
        await _guidUserDal.BulkInsertAsync(users);

        // Assert
        users.All(u => u.Id != Guid.Empty).Should().BeTrue("All users should have generated Guids");
        users.Select(u => u.Id).Distinct().Should().HaveCount(users.Count, "All Guids should be unique");

        // Verify a sample user can be retrieved
        var sampleUser = users[50];
        var retrieved = await _guidUserDal.GetByIdAsync(sampleUser.Id);
        retrieved.Should().NotBeNull();
        retrieved!.Username.Should().Be("bulkuser50");
    }

    [Fact]
    public async Task GetByIdsAsync_WithGuidIds_ShouldRetrieveMultipleRecords()
    {
        // Arrange
        var users = new List<UserWithGuidId>();
        for (int i = 0; i < 10; i++)
        {
            var user = new UserWithGuidId
            {
                Username = $"multiget{i}",
                Email = $"multi{i}@example.com",
                FirstName = $"Multi{i}",
                LastName = "User",
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            };
            await _guidUserDal.InsertAsync(user);
            users.Add(user);
        }

        var userIds = users.Select(u => u.Id).ToList();

        // Act
        var retrieved = await _guidUserDal.GetByIdsAsync(userIds);

        // Assert
        retrieved.Should().HaveCount(10);
        retrieved.Select(u => u.Id).Should().BeEquivalentTo(userIds);
    }

    [Fact]
    public async Task GuidId_ShouldBeUnique_AcrossMultipleInserts()
    {
        // Arrange
        var guids = new HashSet<Guid>();

        // Act - Insert 1000 users rapidly
        for (int i = 0; i < 1000; i++)
        {
            var user = new UserWithGuidId
            {
                Username = $"uniquetest{i}",
                Email = $"unique{i}@example.com",
                FirstName = $"Unique{i}",
                LastName = "Test",
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            };
            await _guidUserDal.InsertAsync(user);
            guids.Add(user.Id);
        }

        // Assert
        guids.Should().HaveCount(1000, "All Guids should be unique");
        guids.Should().NotContain(Guid.Empty, "No Guid should be empty");
    }

    [Fact]
    public async Task MixedPrimaryKeyTypes_ShouldWorkIndependently()
    {
        // Arrange - Insert regular int Id user
        var intUser = new User
        {
            Username = "intuser",
            Email = "int@example.com",
            FirstName = "Int",
            LastName = "User",
            CreatedAt = DateTime.UtcNow,
            IsActive = true
        };
        var userDal = new UserDal(_connection);
        await userDal.InsertAsync(intUser);

        // Arrange - Insert Guid Id user
        var guidUser = new UserWithGuidId
        {
            Username = "guiduser",
            Email = "guid@example.com",
            FirstName = "Guid",
            LastName = "User",
            CreatedAt = DateTime.UtcNow,
            IsActive = true
        };
        await _guidUserDal.InsertAsync(guidUser);

        // Assert
        intUser.Id.Should().BeGreaterThan(0, "Int Id should be auto-increment");
        guidUser.Id.Should().NotBe(Guid.Empty, "Guid Id should be generated");

        // Verify both can be retrieved
        var retrievedInt = await userDal.GetByIdAsync(intUser.Id);
        var retrievedGuid = await _guidUserDal.GetByIdAsync(guidUser.Id);

        retrievedInt.Should().NotBeNull();
        retrievedGuid.Should().NotBeNull();
        retrievedInt!.Username.Should().Be("intuser");
        retrievedGuid!.Username.Should().Be("guiduser");
    }

    public void Dispose()
    {
        _connection?.Dispose();
    }
}
