using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using HighSpeedDAL.Core.Interfaces;

namespace HighSpeedDAL.Core.Base;

/// <summary>
/// Base class for all DAL operations. Provides common SQL execution methods.
/// Entity-specific operations are generated by source generators.
/// </summary>
/// <typeparam name="TEntity">The entity type</typeparam>
/// <typeparam name="TConnection">The database connection type</typeparam>
public abstract class DalOperationsBase<TEntity, TConnection>
    where TEntity : class, new()
    where TConnection : DatabaseConnectionBase
{
    protected readonly TConnection Connection;
    protected readonly ILogger Logger;
    protected readonly IDbConnectionFactory ConnectionFactory;
    protected readonly DalMetricsCollector? MetricsCollector;

    protected DalOperationsBase(
        TConnection connection,
        ILogger logger,
        IDbConnectionFactory connectionFactory,
        DalMetricsCollector? metricsCollector = null)
    {
        Connection = connection ?? throw new ArgumentNullException(nameof(connection));
        Logger = logger ?? throw new ArgumentNullException(nameof(logger));
        ConnectionFactory = connectionFactory ?? throw new ArgumentNullException(nameof(connectionFactory));
        MetricsCollector = metricsCollector;
    }

    /// <summary>
    /// Executes a SQL command with retry logic for transient errors
    /// </summary>
    protected async Task<int> ExecuteNonQueryAsync(
        string sql,
        object? parameters = null,
        IDbTransaction? transaction = null,
        CancellationToken cancellationToken = default)
    {
        IDbConnection? connection = null;
        bool shouldDisposeConnection = transaction == null;

        try
        {
            connection = transaction?.Connection ?? await ConnectionFactory.CreateConnectionAsync(
                Connection.ConnectionString,
                Connection.Provider,
                cancellationToken);

            Logger.LogDebug("Executing SQL: {Sql}", sql);

            using (IDbCommand command = connection.CreateCommand())
            {
                command.CommandText = sql;
                command.CommandType = CommandType.Text;
                command.Transaction = transaction;

                if (parameters != null)
                {
                    AddParameters(command, parameters);
                }

                int result = await ExecuteWithRetryAsync(
                    async () =>
                    {
                        if (command is IDbCommandAsync asyncCommand)
                        {
                            return await asyncCommand.ExecuteNonQueryAsync(cancellationToken);
                        }
                        return command.ExecuteNonQuery();
                    },
                    cancellationToken);

                Logger.LogDebug("SQL executed successfully. Rows affected: {RowsAffected}", result);
                return result;
            }
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Error executing SQL: {Sql}", sql);
            throw;
        }
        finally
        {
            if (shouldDisposeConnection && connection != null)
            {
                connection.Dispose();
            }
        }
    }

    /// <summary>
    /// Executes a SQL query and returns results
    /// </summary>
    protected async Task<List<TResult>> ExecuteQueryAsync<TResult>(
        string sql,
        Func<IDataReader, TResult> mapper,
        object? parameters = null,
        IDbTransaction? transaction = null,
        CancellationToken cancellationToken = default)
    {
        IDbConnection? connection = null;
        bool shouldDisposeConnection = transaction == null;

        try
        {
            connection = transaction?.Connection ?? await ConnectionFactory.CreateConnectionAsync(
                Connection.ConnectionString,
                Connection.Provider,
                cancellationToken);

            Logger.LogDebug("Executing query: {Sql}", sql);

            using (IDbCommand command = connection.CreateCommand())
            {
                command.CommandText = sql;
                command.CommandType = CommandType.Text;
                command.Transaction = transaction;

                if (parameters != null)
                {
                    AddParameters(command, parameters);
                }

                List<TResult> results = await ExecuteWithRetryAsync(
                    async () =>
                    {
                        List<TResult> list = new List<TResult>();

                        IDataReader reader;
                        if (command is IDbCommandAsync asyncCommand)
                        {
                            reader = await asyncCommand.ExecuteReaderAsync(cancellationToken);
                        }
                        else
                        {
                            reader = command.ExecuteReader();
                        }

                        using (reader)
                        {
                            while (reader.Read())
                            {
                                list.Add(mapper(reader));
                            }
                        }

                        return list;
                    },
                    cancellationToken);

                Logger.LogDebug("Query executed successfully. Results: {Count}", results.Count);
                return results;
            }
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Error executing query: {Sql}", sql);
            throw;
        }
        finally
        {
            if (shouldDisposeConnection && connection != null)
            {
                connection.Dispose();
            }
        }
    }

    /// <summary>
    /// Executes a scalar SQL query
    /// </summary>
    protected async Task<TResult?> ExecuteScalarAsync<TResult>(
        string sql,
        object? parameters = null,
        IDbTransaction? transaction = null,
        CancellationToken cancellationToken = default)
    {
        IDbConnection? connection = null;
        bool shouldDisposeConnection = transaction == null;

        try
        {
            connection = transaction?.Connection ?? await ConnectionFactory.CreateConnectionAsync(
                Connection.ConnectionString,
                Connection.Provider,
                cancellationToken);

            Logger.LogDebug("Executing scalar query: {Sql}", sql);

            using (IDbCommand command = connection.CreateCommand())
            {
                command.CommandText = sql;
                command.CommandType = CommandType.Text;
                command.Transaction = transaction;

                if (parameters != null)
                {
                    AddParameters(command, parameters);
                }

                object? result = await ExecuteWithRetryAsync(
                    async () =>
                    {
                        if (command is IDbCommandAsync asyncCommand)
                        {
                            return await asyncCommand.ExecuteScalarAsync(cancellationToken);
                        }
                        return command.ExecuteScalar();
                    },
                    cancellationToken);

                if (result == null || result == DBNull.Value)
                {
                    return default;
                }

                return (TResult)Convert.ChangeType(result, typeof(TResult));
            }
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Error executing scalar query: {Sql}", sql);
            throw;
        }
        finally
        {
            if (shouldDisposeConnection && connection != null)
            {
                connection.Dispose();
            }
        }
    }

    /// <summary>
    /// Executes an operation with retry logic for transient errors
    /// </summary>
    protected abstract Task<TResult> ExecuteWithRetryAsync<TResult>(
        Func<Task<TResult>> operation,
        CancellationToken cancellationToken);

    /// <summary>
    /// Adds parameters to a command from an anonymous object or dictionary
    /// </summary>
    protected abstract void AddParameters(IDbCommand command, object parameters);

    /// <summary>
    /// Creates a transaction for batch operations
    /// </summary>
    public async Task<IDbTransaction> BeginTransactionAsync(CancellationToken cancellationToken = default)
    {
        IDbConnection connection = await ConnectionFactory.CreateConnectionAsync(
            Connection.ConnectionString,
            Connection.Provider,
            cancellationToken);

        Logger.LogDebug("Beginning transaction");
        return connection.BeginTransaction();
    }
}

/// <summary>
/// Interface for async database command execution
/// </summary>
public interface IDbCommandAsync
{
    Task<int> ExecuteNonQueryAsync(CancellationToken cancellationToken);
    Task<IDataReader> ExecuteReaderAsync(CancellationToken cancellationToken);
    Task<object?> ExecuteScalarAsync(CancellationToken cancellationToken);
}
