using System;

namespace HighSpeedDAL.Core.Attributes
{
    /// <summary>
    /// Specifies the data type for the primary key.
    /// Used when auto-generating Id property or specifying requirements for custom primary keys.
    /// </summary>
    public enum PrimaryKeyType
    {
        /// <summary>
        /// Integer primary key with auto-increment (IDENTITY/AUTOINCREMENT).
        /// Default behavior. Suitable for most scenarios.
        /// </summary>
        Int = 0,

        /// <summary>
        /// Globally Unique Identifier (GUID/UUID) primary key.
        /// Generated by application code, not database auto-increment.
        /// Suitable for distributed systems, merging data, offline-first scenarios.
        /// </summary>
        Guid = 1
    }
}
