using FluentAssertions;
using HighSpeedDAL.Core.Interfaces;
using HighSpeedDAL.Core.Resilience;
using HighSpeedDAL.FrameworkUsage.Tests.Data;
using HighSpeedDAL.FrameworkUsage.Tests.Entities;
using HighSpeedDAL.Sqlite;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;

namespace HighSpeedDAL.FrameworkUsage.Tests;

/// <summary>
/// Integration tests demonstrating real-world framework usage with basic CRUD operations.
/// These tests use source-generated DAL classes exactly as users would.
/// 
/// NOTE: Unlike isolated component tests in HighSpeedDAL.Core.Tests, these validate
/// the full stack: Entity attributes ? Source generator ? Generated DAL ? Database
/// 
/// IMPORTANT: These tests demonstrate how developers should use the framework.
/// Copy-paste these patterns into your own projects!
/// </summary>
public class BasicCrudFrameworkTests : IDisposable
{
    private readonly SqliteConnection _connection;
    private readonly TestDatabaseConnection _testConnection;
    private readonly ProductDal _productDal;

    public BasicCrudFrameworkTests()
    {
        // Setup in-memory SQLite connection
        string connectionString = "Data Source=:memory:";
        _connection = new SqliteConnection(connectionString);
        _connection.Open();

        // Use constructor overload for testing that accepts SqliteConnection directly
        _testConnection = new TestDatabaseConnection(_connection);

        // Create table (in production, framework handles this via migrations/scripts)
        CreateProductTable();

        // Create connection factory, retry policy factory, and ProductDal using the generated class
        var connectionFactoryLogger = new Mock<ILogger<SqliteConnectionFactory>>();
        var connectionFactory = new SqliteConnectionFactory(connectionFactoryLogger.Object);

        var retryLogger = new Mock<ILogger<DatabaseRetryPolicy>>();
        var retryPolicyFactory = new RetryPolicyFactory(retryLogger.Object);

        var dalLogger = new Mock<ILogger<ProductDal>>();
        _productDal = new ProductDal(_testConnection, dalLogger.Object, connectionFactory, retryPolicyFactory);
    }

    public void Dispose()
    {
        _connection?.Dispose();
    }

    private void CreateProductTable()
    {
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = @"
            CREATE TABLE Products (
                Id INTEGER PRIMARY KEY AUTOINCREMENT,
                Name TEXT NOT NULL,
                Price REAL NOT NULL,
                StockQuantity INTEGER NOT NULL,
                Category TEXT NOT NULL,
                CreatedDate TEXT NOT NULL,
                IsActive INTEGER NOT NULL DEFAULT 1
            )";
        cmd.ExecuteNonQuery();
    }

    /// <summary>
    /// Demonstrates that source generator created the ProductDal class successfully.
    /// This test validates the full framework stack works.
    /// </summary>
    [Fact]
    public void SourceGenerator_CreatesProductDal_Success()
    {
        // Assert - ProductDal should be generated and instantiable
        _productDal.Should().NotBeNull();
        _productDal.Should().BeOfType<ProductDal>();
    }

    /// <summary>
    /// Demonstrates basic INSERT using generated DAL method.
    /// Users can copy this pattern for their own entities.
    /// </summary>
    [Fact]
    public async Task Insert_UsesGeneratedDalMethod_Success()
    {
        // Arrange - Create entity (no manual Id needed, framework auto-generates)
        var product = new Product
        {
            Name = "Test Product",
            Price = 99.99m,
            StockQuantity = 50,
            Category = "Electronics",
            CreatedDate = DateTime.UtcNow,
            IsActive = true
        };

        // Act - Use generated DAL method (returns entity with Id populated)
        Product inserted = await _productDal.InsertAsync(product);

        // Assert
        inserted.Should().NotBeNull();
        inserted.Id.Should().BeGreaterThan(0); // Auto-generated by database
        inserted.Name.Should().Be("Test Product");
        inserted.Price.Should().Be(99.99m);
    }

    /// <summary>
    /// Demonstrates GetByIdAsync using generated DAL method.
    /// </summary>
    [Fact]
    public async Task GetById_UsesGeneratedDalMethod_Success()
    {
        // Arrange - Insert test data
        var product = new Product
        {
            Name = "Cached Product",
            Price = 49.99m,
            StockQuantity = 100,
            Category = "Books",
            CreatedDate = DateTime.UtcNow
        };
        Product inserted = await _productDal.InsertAsync(product);

        // Act - Use generated DAL method
        var retrieved = await _productDal.GetByIdAsync(inserted.Id);

        // Assert
        retrieved.Should().NotBeNull();
        retrieved!.Id.Should().Be(inserted.Id);
        retrieved.Name.Should().Be("Cached Product");
    }
}
