using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HighSpeedDAL.SourceGenerators.Generators;

/// <summary>
/// Determines which properties need to be auto-generated based on:
/// - Missing Id property (auto-generate int Id)
/// - [Audit] attribute (auto-generate audit properties if missing)
/// - [SoftDelete] attribute (auto-generate soft delete properties if missing)
/// 
/// HighSpeedDAL Framework v0.1
/// </summary>
public sealed class PropertyAutoGenerator
{
    private readonly EntityMetadata _metadata;
    private readonly HashSet<string> _existingPropertyNames;

    public PropertyAutoGenerator(EntityMetadata metadata)
    {
        _metadata = metadata;
        _existingPropertyNames = new HashSet<string>(
            metadata.Properties.Select(p => p.Name),
            System.StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Generates all auto-generated properties as C# source code
    /// </summary>
    public string GenerateAutoProperties()
    {
        StringBuilder sb = new StringBuilder();
        List<PropertyDefinition> autoGeneratedProperties = new List<PropertyDefinition>();

        // 1. Auto-generate Id if missing and no custom PK
        PropertyDefinition idProperty = GenerateIdPropertyIfNeeded();
        if (idProperty != null)
        {
            autoGeneratedProperties.Add(idProperty);
        }

        // 2. Auto-generate Audit properties if [Audit] present
        if (_metadata.HasAuditAttribute)
        {
            List<PropertyDefinition> auditProperties = GenerateAuditPropertiesIfNeeded();
            autoGeneratedProperties.AddRange(auditProperties);
        }

        // 3. Auto-generate SoftDelete properties if [SoftDelete] present
        if (_metadata.HasSoftDeleteAttribute)
        {
            List<PropertyDefinition> softDeleteProperties = GenerateSoftDeletePropertiesIfNeeded();
            autoGeneratedProperties.AddRange(softDeleteProperties);
        }

        // Generate C# code for all auto-generated properties
        foreach (PropertyDefinition property in autoGeneratedProperties)
        {
            sb.AppendLine($@"
        /// <summary>
        /// {property.XmlComment}
        /// AUTO-GENERATED by HighSpeedDAL framework
        /// </summary>
        public {property.TypeName} {property.Name} {{ get; set; }}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Returns list of all properties (existing + auto-generated) for SQL generation
    /// </summary>
    public List<PropertyDefinition> GetAllProperties()
    {
        List<PropertyDefinition> allProperties = new List<PropertyDefinition>(_metadata.Properties);

        // Add auto-generated Id if needed
        PropertyDefinition idProperty = GenerateIdPropertyIfNeeded();
        if (idProperty != null)
        {
            allProperties.Insert(0, idProperty); // Id should be first
        }

        // Add auto-generated audit properties if needed
        if (_metadata.HasAuditAttribute)
        {
            allProperties.AddRange(GenerateAuditPropertiesIfNeeded());
        }

        // Add auto-generated soft delete properties if needed
        if (_metadata.HasSoftDeleteAttribute)
        {
            allProperties.AddRange(GenerateSoftDeletePropertiesIfNeeded());
        }

        return allProperties;
    }

    private PropertyDefinition GenerateIdPropertyIfNeeded()
    {
        // Check if there's already an Id property
        if (PropertyExists("Id"))
        {
            return null; // User provided Id, don't generate
        }

        // Check if there's a custom [PrimaryKey] on another property
        if (_metadata.Properties.Any(p => p.IsPrimaryKey))
        {
            return null; // User specified custom PK, don't generate Id
        }

        // Auto-generate int Id with auto-increment
        return new PropertyDefinition
        {
            Name = "Id",
            TypeName = "int",
            IsPrimaryKey = true,
            IsAutoIncrement = true,
            IsNullable = false,
            XmlComment = "Primary key (auto-increment). Auto-generated by framework."
        };
    }

    private List<PropertyDefinition> GenerateAuditPropertiesIfNeeded()
    {
        List<PropertyDefinition> properties = new List<PropertyDefinition>();

        // CreatedDate
        if (!PropertyExists("CreatedDate"))
        {
            properties.Add(new PropertyDefinition
            {
                Name = "CreatedDate",
                TypeName = "DateTime",
                IsNullable = false,
                XmlComment = "When this record was created. Auto-populated on INSERT."
            });
        }

        // CreatedBy
        if (!PropertyExists("CreatedBy"))
        {
            properties.Add(new PropertyDefinition
            {
                Name = "CreatedBy",
                TypeName = "string",
                IsNullable = false,
                MaxLength = 100,
                XmlComment = "Who created this record. Auto-populated on INSERT."
            });
        }

        // ModifiedDate
        if (!PropertyExists("ModifiedDate"))
        {
            properties.Add(new PropertyDefinition
            {
                Name = "ModifiedDate",
                TypeName = "DateTime",
                IsNullable = false,
                XmlComment = "When this record was last modified. Auto-populated on UPDATE."
            });
        }

        // ModifiedBy
        if (!PropertyExists("ModifiedBy"))
        {
            properties.Add(new PropertyDefinition
            {
                Name = "ModifiedBy",
                TypeName = "string",
                IsNullable = false,
                MaxLength = 100,
                XmlComment = "Who last modified this record. Auto-populated on UPDATE."
            });
        }

        return properties;
    }

    private List<PropertyDefinition> GenerateSoftDeletePropertiesIfNeeded()
    {
        List<PropertyDefinition> properties = new List<PropertyDefinition>();

        // IsDeleted
        if (!PropertyExists("IsDeleted"))
        {
            properties.Add(new PropertyDefinition
            {
                Name = "IsDeleted",
                TypeName = "bool",
                IsNullable = false,
                XmlComment = "Soft delete flag. True if record is deleted. Auto-set on DELETE."
            });
        }

        // DeletedDate
        if (!PropertyExists("DeletedDate"))
        {
            properties.Add(new PropertyDefinition
            {
                Name = "DeletedDate",
                TypeName = "DateTime?",
                IsNullable = true,
                XmlComment = "When this record was soft-deleted. Auto-populated on DELETE."
            });
        }

        // DeletedBy
        if (!PropertyExists("DeletedBy"))
        {
            properties.Add(new PropertyDefinition
            {
                Name = "DeletedBy",
                TypeName = "string",
                IsNullable = true,
                MaxLength = 100,
                XmlComment = "Who soft-deleted this record. Auto-populated on DELETE."
            });
        }

        return properties;
    }

    private bool PropertyExists(string propertyName)
    {
        return _existingPropertyNames.Contains(propertyName);
    }
}

/// <summary>
/// Metadata about an entity class
/// </summary>
public sealed class EntityMetadata
{
    public string ClassName { get; set; }
    public string Namespace { get; set; }
    public string TableName { get; set; }
    public List<PropertyDefinition> Properties { get; set; }
    public bool HasAuditAttribute { get; set; }
    public bool HasSoftDeleteAttribute { get; set; }
    public bool IsReferenceTable { get; set; }
    public string CsvFilePath { get; set; }
    public string MergeStrategy { get; set; }

    public EntityMetadata()
    {
        Properties = new List<PropertyDefinition>();
        ClassName = string.Empty;
        Namespace = string.Empty;
        TableName = string.Empty;
        CsvFilePath = string.Empty;
        MergeStrategy = "MergeOrInsert";
    }
}

/// <summary>
/// Metadata about a property
/// </summary>
public sealed class PropertyDefinition
{
    public string Name { get; set; }
    public string TypeName { get; set; }
    public bool IsPrimaryKey { get; set; }
    public bool IsAutoIncrement { get; set; }
    public bool IsNullable { get; set; }
    public int? MaxLength { get; set; }
    public string XmlComment { get; set; }

    public PropertyDefinition()
    {
        Name = string.Empty;
        TypeName = string.Empty;
        XmlComment = string.Empty;
    }
}
