using System.Linq;
using System.Text;
using HighSpeedDAL.SourceGenerators.Models;

namespace HighSpeedDAL.SourceGenerators.Generation;

/// <summary>
/// Generates complete DAL class code for an entity
/// </summary>
internal sealed partial class DalClassGenerator
{
    private readonly EntityMetadata _metadata;
    private readonly SqlGenerator _sqlGenerator;
    private readonly string _connectionClassName;
    private readonly string? _connectionClassFullName;
    private readonly DatabaseProvider _databaseProvider;

    /// <summary>
    /// Gets the primary key type (int, Guid, etc.) for the entity
    /// Returns normalized C# type name: "int" for integer types, "Guid" for Guid types
    /// </summary>
    private string PrimaryKeyType
    {
        get
        {
            // If we have an explicit primary key property, use its type
            if (_metadata.PrimaryKeyProperty?.PropertyType != null)
            {
                string propType = _metadata.PrimaryKeyProperty.PropertyType;
                // Normalize type names for consistency
                if (propType == "System.Guid" || propType == "Guid")
                    return "Guid";
                if (propType == "Int32" || propType == "System.Int32" || propType == "int")
                    return "int";
                if (propType == "Int64" || propType == "System.Int64" || propType == "long")
                    return "long";
                return propType;
            }

            // Fall back to metadata's PrimaryKeyType setting
            return _metadata.PrimaryKeyType == "Guid" ? "Guid" : "int";
        }
    }

    public DalClassGenerator(
        EntityMetadata metadata, 
        string connectionClassName, 
        string? connectionClassFullName = null,
        DatabaseProvider databaseProvider = DatabaseProvider.SqlServer)
    {
        _metadata = metadata;
        _connectionClassName = connectionClassName;
        _connectionClassFullName = connectionClassFullName;
        _databaseProvider = databaseProvider;

        // Pass provider to SqlGenerator as string
        string providerName = databaseProvider == DatabaseProvider.Sqlite ? "Sqlite" : "SqlServer";
        _sqlGenerator = new SqlGenerator(metadata, providerName);
    }

    public string GenerateDalClass()
    {
        StringBuilder code = new StringBuilder();

        // File header
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        code.AppendLine();

        // Usings
        GenerateUsings(code);
        code.AppendLine();

        // Namespace
        code.AppendLine($"namespace {_metadata.Namespace};");
        code.AppendLine();

        // Class declaration - choose base class based on database provider
        string baseClass = _databaseProvider == DatabaseProvider.Sqlite
            ? $"SqliteDalBase<{_metadata.ClassName}, {_connectionClassName}>"
            : $"SqlServerDalBase<{_metadata.ClassName}, {_connectionClassName}>";

        if (_metadata.IsReferenceTable)
        {
            code.AppendLine($"/// <summary>");
            code.AppendLine($"/// Generated DAL for {_metadata.ClassName} reference table");
            code.AppendLine($"/// </summary>");
        }
        else
        {
            code.AppendLine($"/// <summary>");
            code.AppendLine($"/// Generated DAL for {_metadata.ClassName} entity");
            code.AppendLine($"/// </summary>");
        }

        code.AppendLine($"public sealed partial class {_metadata.ClassName}Dal : {baseClass}");
        code.AppendLine("{");

        // Fields
        GenerateFields(code);
        code.AppendLine();

        // Constructor
        GenerateConstructor(code);
        code.AppendLine();

        // SQL constants
        GenerateSqlConstants(code);
        code.AppendLine();

        // Schema initialization
        GenerateSchemaInitialization(code);
        code.AppendLine();

        // CRUD methods
        GenerateGetByIdMethod(code);
        code.AppendLine();

        GenerateGetAllMethod(code);
        code.AppendLine();

        GenerateInsertMethod(code);
        code.AppendLine();

        GenerateUpdateMethod(code);
        code.AppendLine();

        GenerateDeleteMethod(code);
        code.AppendLine();

        GenerateBulkInsertMethod(code);
        code.AppendLine();

        GenerateBulkInsertWithDuplicatesMethod(code);
        code.AppendLine();

        GenerateCountMethod(code);
        code.AppendLine();

        GenerateExistsMethod(code);
        code.AppendLine();

        // Additional query methods
        GenerateGetByIdsMethod(code);
        code.AppendLine();

        // Bulk operations
        GenerateBulkUpdateMethod(code);
        code.AppendLine();

        GenerateBulkDeleteMethod(code);
        code.AppendLine();

        // Soft delete specific methods
        if (_metadata.HasSoftDelete)
        {
            GenerateHardDeleteMethod(code);
            code.AppendLine();

            GenerateGetAllIncludingDeletedMethod(code);
            code.AppendLine();
        }

        // Reference table specific methods
        if (_metadata.IsReferenceTable)
        {
            GenerateGetByNameMethod(code);
            code.AppendLine();

            GeneratePreloadDataMethod(code);
            code.AppendLine();
        }

        // Named query methods
        GenerateNamedQueryMethods(code);

        // In-memory helper methods
        if (_metadata.HasInMemoryTable)
        {
            GenerateGetAllFromDatabaseAsyncMethod(code);
            code.AppendLine();
        }

            // Helper methods
            GenerateMapFromReaderMethod(code);
            code.AppendLine();

            GenerateMapToParametersMethod(code);

            if (_metadata.HasMemoryMappedTable)
            {
                code.AppendLine();
                GenerateMemoryMappedHelperMethods(code);
            }

            // Close class
            code.AppendLine("}");

            return code.ToString();
        }

    private void GenerateUsings(StringBuilder code)
    {
        code.AppendLine("using System;");
        code.AppendLine("using System.Collections.Generic;");
        code.AppendLine("using System.Data;");
        code.AppendLine("using System.Linq;");
        code.AppendLine("using System.Threading;");
        code.AppendLine("using System.Threading.Tasks;");
        code.AppendLine("using HighSpeedDAL.Core;");
        code.AppendLine("using HighSpeedDAL.Core.Base;");
        code.AppendLine("using HighSpeedDAL.Core.Interfaces;");
        code.AppendLine("using HighSpeedDAL.Core.Resilience;");

        // Include the appropriate database provider namespace
        if (_databaseProvider == DatabaseProvider.Sqlite)
        {
            code.AppendLine("using HighSpeedDAL.Sqlite;");
        }
        else
        {
            code.AppendLine("using HighSpeedDAL.SqlServer;");
        }

        code.AppendLine("using Microsoft.Extensions.Logging;");
        code.AppendLine("using ExpressRecipe.Data.Common;");

        if (_metadata.HasCache)
        {
            code.AppendLine("using HighSpeedDAL.Core.Caching;");
        }

        // In-memory table support (RAM-only, no persistence)
        if (_metadata.HasInMemoryTable)
        {
            code.AppendLine("using HighSpeedDAL.Core.InMemoryTable;");
        }

        if (_metadata.HasMemoryMappedTable)
        {
            code.AppendLine("using HighSpeedDAL.Core.InMemoryTable;");
            code.AppendLine("using HighSpeedDAL.Core.Attributes;");
        }

            // Add connection class namespace if it's different from entity namespace
            if (!string.IsNullOrWhiteSpace(_connectionClassFullName))
            {
                string connectionNamespace = GetNamespaceFromFullName(_connectionClassFullName!);
                if (!string.IsNullOrWhiteSpace(connectionNamespace) && connectionNamespace != _metadata.Namespace)
                {
                    code.AppendLine($"using {connectionNamespace};");
                }
            }
        }

    private string GetNamespaceFromFullName(string fullName)
    {
        int lastDot = fullName.LastIndexOf('.');
        return lastDot > 0 ? fullName.Substring(0, lastDot) : string.Empty;
    }

    private void GenerateFields(StringBuilder code)
    {
        // In-memory table field (RAM-only, no persistence)
        if (_metadata.HasInMemoryTable)
        {
            code.AppendLine($"    private InMemoryTable<{_metadata.ClassName}>? _inMemoryTable;");
            code.AppendLine();
        }

        if (_metadata.HasMemoryMappedTable)
        {
            code.AppendLine($"    private readonly MemoryMappedFileStore<{_metadata.ClassName}>? _memoryMappedStore;");
            code.AppendLine($"    private readonly System.Collections.Concurrent.ConcurrentDictionary<{PrimaryKeyType}, {_metadata.ClassName}> _l0Cache = new();");
            code.AppendLine("    private System.Threading.Timer? _memoryMappedSyncTimer;");
            code.AppendLine();
        }

        if (_metadata.HasCache)
        {
            code.AppendLine($"    private readonly ICacheManager<{_metadata.ClassName}, {PrimaryKeyType}> _cache;");

            // Expose cache publicly for benchmarking/testing
            code.AppendLine($"    /// <summary>");
            code.AppendLine($"    /// Gets access to the underlying cache manager");
            code.AppendLine($"    /// </summary>");
            code.AppendLine($"    public ICacheManager<{_metadata.ClassName}, {PrimaryKeyType}> Cache => _cache;");
        }

        code.AppendLine("    private static bool _schemaInitialized = false;");
        code.AppendLine("    private static readonly object _schemaLock = new object();");
    }

    private void GenerateConstructor(StringBuilder code)
    {
        code.AppendLine($"    public {_metadata.ClassName}Dal(");
        code.AppendLine($"        {_connectionClassName} connection,");
        code.AppendLine($"        ILogger<{_metadata.ClassName}Dal> logger,");
        code.AppendLine("        IDbConnectionFactory connectionFactory,");
        code.AppendLine("        RetryPolicyFactory retryPolicyFactory,");
        code.AppendLine("        DalMetricsCollector? metricsCollector = null");

        if (_metadata.HasMemoryMappedTable)
        {
            code.AppendLine("        , ILoggerFactory? loggerFactory = null)");
        }
        else
        {
            code.AppendLine(")");
        }

        code.AppendLine($"        : base(connection, logger, connectionFactory, retryPolicyFactory.CreatePolicy(), metricsCollector)");
        code.AppendLine("    {");

        if (_metadata.HasMemoryMappedTable)
        {
            code.AppendLine("        // Initialize memory-mapped L0 cache (mandatory when attribute present)");
            code.AppendLine("        // Use simplified constructor without InMemoryTableAttribute for DAL scenario");
            code.AppendLine($"        var mmfConfig = new InMemoryTableAttribute");
            code.AppendLine("        {");
            code.AppendLine($"            MemoryMappedFileSizeMB = {_metadata.MemoryMappedSizeMB}");
            code.AppendLine("        };");
            code.AppendLine($"        _memoryMappedStore = new MemoryMappedFileStore<{_metadata.ClassName}>(");
            code.AppendLine($"            \"{_metadata.MemoryMappedFileName}\",");
            code.AppendLine("            mmfConfig,");
            code.AppendLine($"            loggerFactory.CreateLogger<MemoryMappedFileStore<{_metadata.ClassName}>>(),");
            code.AppendLine($"            loggerFactory.CreateLogger<MemoryMappedSynchronizer>());");
            code.AppendLine();

            if (_metadata.MemoryMappedAutoLoadOnStartup)
            {
                code.AppendLine("        // Auto-load from memory-mapped file into L0 cache on startup");
                code.AppendLine("        Task.Run(async () =>");
                code.AppendLine("        {");
                code.AppendLine("            try");
                code.AppendLine("            {");
                code.AppendLine("                var rows = await _memoryMappedStore.LoadAsync();");
                code.AppendLine("                foreach (var row in rows)");
                code.AppendLine("                {");
                code.AppendLine($"                    _l0Cache.TryAdd(row.{_metadata.PrimaryKeyProperty?.PropertyName ?? "Id"}, row);");
                code.AppendLine("                }");
                code.AppendLine($"                logger.LogInformation(\"Loaded {{Count}} rows from memory-mapped file into L0 cache for {_metadata.ClassName}\", rows.Count);");
                code.AppendLine("            }");
                code.AppendLine("            catch (Exception ex)");
                code.AppendLine("            {");
                code.AppendLine($"                logger.LogWarning(ex, \"Failed to load memory-mapped file for {_metadata.ClassName}, starting with empty L0 cache\");");
                code.AppendLine("            }");
                code.AppendLine("        }).Wait();");
                code.AppendLine();
            }

            if (_metadata.MemoryMappedSyncMode == 1) // Batched
            {
                code.AppendLine($"        // Setup timer for batched sync mode (every {_metadata.MemoryMappedFlushIntervalSeconds} seconds)");
                code.AppendLine($"        _memoryMappedSyncTimer = new System.Threading.Timer(");
                code.AppendLine("            async _ =>");
                code.AppendLine("            {");
                code.AppendLine("                try");
                code.AppendLine("                {");
                code.AppendLine("                    await FlushMemoryMappedCacheAsync();");
                code.AppendLine("                }");
                code.AppendLine("                catch (Exception ex)");
                code.AppendLine("                {");
                code.AppendLine($"                    logger.LogError(ex, \"Failed to flush memory-mapped cache for {_metadata.ClassName}\");");
                code.AppendLine("                }");
                code.AppendLine("            },");
                code.AppendLine("            state: null,");
                code.AppendLine($"            dueTime: TimeSpan.FromSeconds({_metadata.MemoryMappedFlushIntervalSeconds}),");
                code.AppendLine($"            period: TimeSpan.FromSeconds({_metadata.MemoryMappedFlushIntervalSeconds}));");
                code.AppendLine();
            }
        }

        if (_metadata.HasCache)
        {
            string cacheType = _metadata.CacheStrategy == "TwoLayer"
                ? "TwoLayerCacheManager"
                : "MemoryCacheManager";

            code.AppendLine($"        _cache = new {cacheType}<{_metadata.ClassName}, {PrimaryKeyType}>(");
            code.AppendLine($"            logger,");
            code.AppendLine($"            maxSize: {_metadata.CacheMaxSize},");

            if (_metadata.CacheStrategy == "TwoLayer")
            {
                code.AppendLine($"            expirationSeconds: {_metadata.CacheExpirationSeconds},");
                code.AppendLine($"            promotionIntervalSeconds: {_metadata.CachePromotionIntervalSeconds});");
            }
            else
            {
                code.AppendLine($"            expirationSeconds: {_metadata.CacheExpirationSeconds});");
            }

            code.AppendLine();
        }

        // In-memory table initialization
        if (_metadata.HasInMemoryTable)
        {
            code.AppendLine("        // Initialize in-memory table (RAM-only, no persistence)");
            code.AppendLine($"        _inMemoryTable = new InMemoryTable<{_metadata.ClassName}>(");
            code.AppendLine("            logger,");
            code.AppendLine("            null,");
            code.AppendLine($"            \"{_metadata.TableName}\");");
            code.AppendLine();
            code.AppendLine("        // Load data from database on startup");
            code.AppendLine("        Task.Run(async () =>");
            code.AppendLine("        {");
            code.AppendLine("            try");
            code.AppendLine("            {");
            code.AppendLine($"                logger.LogInformation(\"Loading {_metadata.TableName} data into memory...\");");
            code.AppendLine("                var allRows = await GetAllFromDatabaseAsync(CancellationToken.None);");
            code.AppendLine("                foreach (var row in allRows)");
            code.AppendLine("                {");
            code.AppendLine("                    await _inMemoryTable.InsertAsync(row);");
            code.AppendLine("                }");
            code.AppendLine($"                logger.LogInformation(\"Loaded {{Count}} rows into memory for {_metadata.TableName}\", allRows.Count);");
            code.AppendLine("            }");
            code.AppendLine("            catch (Exception ex)");
            code.AppendLine("            {");
            code.AppendLine($"                logger.LogError(ex, \"Failed to load {_metadata.TableName} into memory. Falling back to database.\");");
            code.AppendLine("                _inMemoryTable = null; // Disable in-memory if load fails");
            code.AppendLine("            }");
            code.AppendLine("        }).Wait();");
            code.AppendLine();
        }

        code.AppendLine("        // Ensure schema is initialized");
        code.AppendLine("        Task.Run(() => EnsureSchemaAsync()).Wait();");

        if (_metadata.IsReferenceTable && _metadata.ReferenceLoadFromCode)
        {
            code.AppendLine();
            code.AppendLine("        // Preload reference data");
            code.AppendLine("        Task.Run(() => PreloadDataAsync()).Wait();");
        }

        code.AppendLine("    }");
    }

    private void GenerateSqlConstants(StringBuilder code)
    {
        code.AppendLine("    // SQL Statements");
        code.AppendLine($"    private const string SQL_INSERT = @\"{_sqlGenerator.GenerateInsertSql().Replace("\"", "\"\"")}\";");
        code.AppendLine($"    private const string SQL_UPDATE = @\"{_sqlGenerator.GenerateUpdateSql().Replace("\"", "\"\"")}\";");
        code.AppendLine($"    private const string SQL_DELETE = @\"{_sqlGenerator.GenerateDeleteSql().Replace("\"", "\"\"")}\";");
        code.AppendLine($"    private const string SQL_GET_BY_ID = @\"{_sqlGenerator.GenerateGetByIdSql().Replace("\"", "\"\"")}\";");
        code.AppendLine($"    private const string SQL_GET_ALL = @\"{_sqlGenerator.GenerateGetAllSql().Replace("\"", "\"\"")}\";");
        code.AppendLine($"    private const string SQL_COUNT = @\"{_sqlGenerator.GenerateCountSql().Replace("\"", "\"\"")}\";");
        code.AppendLine($"    private const string SQL_EXISTS = @\"{_sqlGenerator.GenerateExistsSql().Replace("\"", "\"\"")}\";");
        code.AppendLine($"    private const string SQL_GET_BY_IDS = @\"{_sqlGenerator.GenerateGetByIdsSql().Replace("\"", "\"\"")}\";");
        code.AppendLine($"    private const string SQL_BULK_DELETE = @\"{_sqlGenerator.GenerateBulkDeleteSql().Replace("\"", "\"\"")}\";");

        if (_metadata.HasSoftDelete)
        {
            code.AppendLine($"    private const string SQL_HARD_DELETE = @\"{_sqlGenerator.GenerateHardDeleteSql().Replace("\"", "\"\"")}\";");
            code.AppendLine($"    private const string SQL_GET_ALL_INCLUDING_DELETED = @\"{_sqlGenerator.GenerateGetAllIncludingDeletedSql().Replace("\"", "\"\"")}\";");
        }

        if (_metadata.IsReferenceTable)
        {
            code.AppendLine($"    private const string SQL_GET_BY_NAME = @\"{_sqlGenerator.GenerateGetByNameSql().Replace("\"", "\"\"")}\";");
        }

        code.AppendLine();
        code.AppendLine($"    private const string SQL_CREATE_TABLE = @\"{_sqlGenerator.GenerateCreateTableSql().Replace("\"", "\"\"")}\";");

        // Generate named query SQL constants
        GenerateNamedQuerySqlConstants(code);
    }

    private void GenerateSchemaInitialization(StringBuilder code)
    {
        code.AppendLine("    private async Task EnsureSchemaAsync(CancellationToken cancellationToken = default)");
        code.AppendLine("    {");
        code.AppendLine("        if (_schemaInitialized)");
        code.AppendLine("        {");
        code.AppendLine("            return;");
        code.AppendLine("        }");
        code.AppendLine();
        code.AppendLine("        lock (_schemaLock)");
        code.AppendLine("        {");
        code.AppendLine("            if (_schemaInitialized)");
        code.AppendLine("            {");
        code.AppendLine("                return;");
        code.AppendLine("            }");
        code.AppendLine();
        code.AppendLine("            try");
        code.AppendLine("            {");
        code.AppendLine($"                Logger.LogInformation(\"Initializing schema for table {_metadata.TableName}\");");
        code.AppendLine();

        code.AppendLine("                // Check if tables should be dropped (configured in appsettings)");
        code.AppendLine("                if (Connection.ShouldDropTablesOnStartup)");
        code.AppendLine("                {");
        code.AppendLine("                    // Drop table if exists");
        code.AppendLine($"                    string dropSql = \"DROP TABLE IF EXISTS [{_metadata.TableName}]\";");
        code.AppendLine("                    Task.Run(async () => await ExecuteNonQueryAsync(dropSql, cancellationToken: cancellationToken)).Wait();");
        code.AppendLine($"                    Logger.LogWarning(\"Table {_metadata.TableName} dropped (DropTablesOnStartup=true)\");");
        code.AppendLine("                }");
        code.AppendLine();

        if (_metadata.AutoCreate)
        {
            code.AppendLine("                // Create table if not exists");
            code.AppendLine("                Task.Run(async () => await ExecuteNonQueryAsync(SQL_CREATE_TABLE, cancellationToken: cancellationToken)).Wait();");
            code.AppendLine($"                Logger.LogInformation(\"Table {_metadata.TableName} created or already exists\");");
        }

        code.AppendLine();
        code.AppendLine("                _schemaInitialized = true;");
        code.AppendLine("            }");
        code.AppendLine("            catch (Exception ex)");
        code.AppendLine("            {");
        code.AppendLine($"                Logger.LogError(ex, \"Failed to initialize schema for {_metadata.TableName}\");");
        code.AppendLine("                throw;");
        code.AppendLine("            }");
        code.AppendLine("        }");
        code.AppendLine("    }");
    }

    private void GenerateGetByIdMethod(StringBuilder code)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine($"    /// Gets a {_metadata.ClassName} by ID");
        code.AppendLine("    /// </summary>");
        code.AppendLine($"    public async Task<{_metadata.ClassName}?> GetByIdAsync({PrimaryKeyType} id, CancellationToken cancellationToken = default)");
        code.AppendLine("    {");
        code.AppendLine("        var stopwatch = System.Diagnostics.Stopwatch.StartNew();");

        // In-memory table check (highest priority)
        if (_metadata.HasInMemoryTable)
        {
            code.AppendLine("        // Check in-memory table FIRST (highest priority)");
            code.AppendLine("        if (_inMemoryTable != null)");
            code.AppendLine("        {");
            code.AppendLine("            try");
            code.AppendLine("            {");
            code.AppendLine("                stopwatch.Restart();");
            code.AppendLine("                var inMemoryResult = _inMemoryTable.GetById(id);");
            code.AppendLine("                stopwatch.Stop();");
            code.AppendLine("                if (inMemoryResult != null)");
            code.AppendLine("                {");
            code.AppendLine($"                    Logger.LogDebug(\"In-memory table hit for {_metadata.ClassName} ID: {{Id}} in {{ElapsedMs}}ms\", id, stopwatch.ElapsedMilliseconds);");
            code.AppendLine($"                    MetricsCollector?.RecordCacheHit(\"{_metadata.TableName}\");");
            code.AppendLine($"                    MetricsCollector?.RecordOperationDuration(\"{_metadata.TableName}\", \"GetById_Memory\", stopwatch.ElapsedMilliseconds);");
            code.AppendLine($"                    DataSourceLogger.LogMemoryRead(Logger, \"{_metadata.TableName}\", \"GetByIdAsync\", id, 1);");
            code.AppendLine("                    return inMemoryResult;");
            code.AppendLine("                }");
            code.AppendLine("            }");
            code.AppendLine("            catch (Exception ex)");
            code.AppendLine("            {");
            code.AppendLine($"                Logger.LogWarning(ex, \"In-memory table lookup failed for {_metadata.ClassName} ID: {{Id}}, falling back to database\", id);");
            code.AppendLine("            }");
            code.AppendLine("        }");
            code.AppendLine();
        }

        if (_metadata.HasMemoryMappedTable)
        {
            code.AppendLine("        // Check L0 cache (memory-mapped backed)");
            code.AppendLine("        if (_l0Cache.TryGetValue(id, out var l0Cached))");
            code.AppendLine("        {");
            code.AppendLine($"            Logger.LogDebug(\"L0 cache hit (memory-mapped) for {_metadata.ClassName} ID: {{Id}}\", id);");
            code.AppendLine($"            MetricsCollector?.RecordCacheHit(\"{_metadata.TableName}\");");
            code.AppendLine("            return l0Cached;");
            code.AppendLine("        }");
            code.AppendLine();
        }

        if (_metadata.HasCache)
        {
            code.AppendLine("        // Check L1/L2 cache");
            code.AppendLine($"        {_metadata.ClassName}? cached = await _cache.GetAsync(id, cancellationToken);");
            code.AppendLine("        if (cached != null)");
            code.AppendLine("        {");
            code.AppendLine($"            Logger.LogDebug(\"Cache hit for {_metadata.ClassName} ID: {{Id}}\", id);");
            code.AppendLine($"            MetricsCollector?.RecordCacheHit(\"{_metadata.TableName}\");");
            code.AppendLine("            return cached;");
            code.AppendLine("        }");
            code.AppendLine();
            code.AppendLine($"        MetricsCollector?.RecordCacheMiss(\"{_metadata.TableName}\");");
            code.AppendLine();
        }

        code.AppendLine($"        Logger.LogDebug(\"Retrieving {_metadata.ClassName} by ID: {{Id}}\", id);");
        code.AppendLine();
        code.AppendLine("        Dictionary<string, object> parameters = new Dictionary<string, object>");
        code.AppendLine("        {");
        code.AppendLine("            { \"Id\", id }");
        code.AppendLine("        };");
        code.AppendLine();
        code.AppendLine("        stopwatch.Restart();");
        code.AppendLine($"        List<{_metadata.ClassName}> results = await ExecuteQueryAsync(");
        code.AppendLine("            SQL_GET_BY_ID,");
        code.AppendLine("            MapFromReader,");
        code.AppendLine("            parameters,");
        code.AppendLine("            transaction: null,");
        code.AppendLine("            cancellationToken);");
        code.AppendLine("        stopwatch.Stop();");
        code.AppendLine();
        code.AppendLine($"        {_metadata.ClassName}? entity = results.FirstOrDefault();");
        code.AppendLine();
        code.AppendLine("        // Log database read operation");
        code.AppendLine($"        DataSourceLogger.LogDatabaseRead(Logger, \"{_metadata.TableName}\", \"GetByIdAsync\", id, entity != null ? 1 : 0);");
        code.AppendLine();
        code.AppendLine("        // Record metrics with timing and data source tag");
        code.AppendLine($"        MetricsCollector?.RecordOperation(\"{_metadata.TableName}\", \"GetById_Database\", entity != null ? 1 : 0);");
        code.AppendLine($"        MetricsCollector?.RecordOperationDuration(\"{_metadata.TableName}\", \"GetById_Database\", stopwatch.ElapsedMilliseconds);");

            if (_metadata.HasCache)
            {
                code.AppendLine();
                code.AppendLine("        // Cache the result");
                code.AppendLine("        if (entity != null)");
                code.AppendLine("        {");
                code.AppendLine("            await _cache.SetAsync(id, entity, cancellationToken);");
                code.AppendLine("        }");
            }

            if (_metadata.HasMemoryMappedTable)
            {
                code.AppendLine();
                code.AppendLine("        // Update L0 cache (memory-mapped) if not read-only");
                code.AppendLine("        if (entity != null && _memoryMappedStore != null)");
                code.AppendLine("        {");
                code.AppendLine("            await UpdateMemoryMappedCacheAsync(entity, cancellationToken);");
                code.AppendLine("        }");
            }

            code.AppendLine();
            code.AppendLine("        return entity;");
            code.AppendLine("    }");
        }

    private void GenerateGetAllMethod(StringBuilder code)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine($"    /// Gets all {_metadata.ClassName} entities");
        code.AppendLine("    /// </summary>");
        code.AppendLine($"    public async Task<List<{_metadata.ClassName}>> GetAllAsync(CancellationToken cancellationToken = default)");
        code.AppendLine("    {");
        code.AppendLine("        var stopwatch = System.Diagnostics.Stopwatch.StartNew();");

        // Return from in-memory table if available
        if (_metadata.HasInMemoryTable)
        {
            code.AppendLine("        // Return from in-memory table if available");
            code.AppendLine("        if (_inMemoryTable != null)");
            code.AppendLine("        {");
            code.AppendLine("            try");
            code.AppendLine("            {");
            code.AppendLine("                stopwatch.Restart();");
            code.AppendLine("                var allInMemory = _inMemoryTable.Select().ToList();");
            code.AppendLine("                stopwatch.Stop();");
            code.AppendLine($"                Logger.LogInformation(\"Returning {{Count}} rows from in-memory table for {_metadata.ClassName} in {{ElapsedMs}}ms\", allInMemory.Count, stopwatch.ElapsedMilliseconds);");
            code.AppendLine($"                DataSourceLogger.LogMemoryRead(Logger, \"{_metadata.TableName}\", \"GetAllAsync\", null, allInMemory.Count);");
            code.AppendLine();
            code.AppendLine("                // Record metrics with timing and data source tag");
            code.AppendLine($"                MetricsCollector?.RecordOperation(\"{_metadata.TableName}\", \"GetAll_Memory\", allInMemory.Count);");
            code.AppendLine($"                MetricsCollector?.RecordOperationDuration(\"{_metadata.TableName}\", \"GetAll_Memory\", stopwatch.ElapsedMilliseconds);");
            code.AppendLine($"                MetricsCollector?.SetItemCount(\"{_metadata.TableName}\", allInMemory.Count);");
            code.AppendLine();
            code.AppendLine("                return allInMemory;");
            code.AppendLine("            }");
            code.AppendLine("            catch (Exception ex)");
            code.AppendLine("            {");
            code.AppendLine($"                Logger.LogWarning(ex, \"Failed to retrieve from in-memory table, falling back to database\");");
            code.AppendLine("            }");
            code.AppendLine("        }");
            code.AppendLine();
        }

        code.AppendLine($"        Logger.LogDebug(\"Retrieving all {_metadata.ClassName} entities from database\");");
        code.AppendLine();
        code.AppendLine("        stopwatch.Restart();");
        code.AppendLine($"        List<{_metadata.ClassName}> results = await ExecuteQueryAsync(");
        code.AppendLine("            SQL_GET_ALL,");
        code.AppendLine("            MapFromReader,");
        code.AppendLine("            parameters: null,");
        code.AppendLine("            transaction: null,");
        code.AppendLine("            cancellationToken);");
        code.AppendLine("        stopwatch.Stop();");
        code.AppendLine();
        code.AppendLine($"        Logger.LogDebug(\"Retrieved {{Count}} {_metadata.ClassName} entities from database in {{ElapsedMs}}ms\", results.Count, stopwatch.ElapsedMilliseconds);");
        code.AppendLine();
        code.AppendLine("        // Log database read operation");
        code.AppendLine($"        DataSourceLogger.LogDatabaseRead(Logger, \"{_metadata.TableName}\", \"GetAllAsync\", null, results.Count);");
        code.AppendLine();
        code.AppendLine("        // Record metrics with timing and data source tag");
        code.AppendLine($"        MetricsCollector?.RecordOperation(\"{_metadata.TableName}\", \"GetAll_Database\", results.Count);");
        code.AppendLine($"        MetricsCollector?.RecordOperationDuration(\"{_metadata.TableName}\", \"GetAll_Database\", stopwatch.ElapsedMilliseconds);");
        code.AppendLine($"        MetricsCollector?.SetItemCount(\"{_metadata.TableName}\", results.Count);");
        code.AppendLine();
        code.AppendLine("        return results;");
        code.AppendLine("    }");
    }

    // Continue in Part 2...
}
