using System.Collections.Generic;
using System.Linq;
using System.Text;
using HighSpeedDAL.SourceGenerators.Models;

namespace HighSpeedDAL.SourceGenerators.Generation
{
    /// <summary>
    /// Generates partial entity class with auto-generated properties for audit and soft delete
    /// </summary>
    internal sealed class EntityPropertyGenerator
    {
        private readonly EntityMetadata _metadata;
        private readonly List<PropertyMetadata> _missingProperties;

        public EntityPropertyGenerator(EntityMetadata metadata, List<PropertyMetadata> missingProperties)
        {
            _metadata = metadata;
            _missingProperties = missingProperties;
        }

        /// <summary>
        /// Generates a partial class with missing audit/soft delete properties
        /// </summary>
        public string GeneratePartialClass()
        {
            if (_missingProperties.Count == 0)
            {
                return string.Empty;
            }

            StringBuilder code = new StringBuilder();

            // File header
            code.AppendLine("// <auto-generated />");
            code.AppendLine("// Auto-generated properties for entities with [Table], [AutoAudit], and [SoftDelete] attributes");
            code.AppendLine("#nullable enable");
            code.AppendLine();

            // Using statements
            code.AppendLine("using System;");

            // Add HighSpeedDAL using if custom columns, primary keys, or identity columns are used
            bool needsFrameworkUsing = _missingProperties.Any(p => 
                p.ColumnName != p.PropertyName || 
                p.IsPrimaryKey || 
                p.IsAutoIncrement);

            if (needsFrameworkUsing)
            {
                code.AppendLine("using HighSpeedDAL.Core.Attributes;");
            }
        
            code.AppendLine();

            // Namespace
            code.AppendLine($"namespace {_metadata.Namespace}");
            code.AppendLine("{");

            // Partial class declaration
            code.AppendLine($"    /// <summary>");
            code.AppendLine($"    /// Auto-generated properties for {_metadata.ClassName}");
            code.AppendLine($"    /// </summary>");
            code.AppendLine($"    public partial class {_metadata.ClassName}");
            code.AppendLine("    {");

                // Generate each missing property
                foreach (PropertyMetadata property in _missingProperties)
                {
                    GenerateProperty(code, property);
                }

                // Close class
                code.AppendLine("    }");

                // Close namespace
                code.AppendLine("}");

                    return code.ToString();
                }

                /// <summary>
                /// Generates a partial class with ONLY clone methods (for all entities)
                /// </summary>
                public string GenerateCloneMethods()
                {
                    StringBuilder code = new StringBuilder();

                    // File header
                    code.AppendLine("// <auto-generated />");
                    code.AppendLine("// Auto-generated clone methods for defensive copying in caches");
                    code.AppendLine("#nullable enable");
                    code.AppendLine();

                    // Using statements
                    code.AppendLine("using System;");
                    code.AppendLine("using System.Linq;");
                    code.AppendLine("using System.Collections.Generic;");
                    code.AppendLine("using HighSpeedDAL.Core.Interfaces;");
                    code.AppendLine();

                    // Namespace
                    code.AppendLine($"namespace {_metadata.Namespace}");
                    code.AppendLine("{");

                    // Partial class declaration with IEntityCloneable interface
                    code.AppendLine($"    /// <summary>");
                    code.AppendLine($"    /// Clone methods for {_metadata.ClassName}");
                    code.AppendLine($"    /// </summary>");
                    code.AppendLine($"    public partial class {_metadata.ClassName} : IEntityCloneable<{_metadata.ClassName}>");
                    code.AppendLine("    {");

                    // Generate clone methods
                    GenerateCloneMethodsInternal(code);

                    // Close class
                    code.AppendLine("    }");

                    // Close namespace
                    code.AppendLine("}");

                    return code.ToString();
                }

                private void GenerateProperty(StringBuilder code, PropertyMetadata property)
                {
                    // XML documentation
                    code.AppendLine($"        /// <summary>");

                    string description = GetPropertyDescription(property.PropertyName);
                    code.AppendLine($"        /// {description}");
                    code.AppendLine($"        /// AUTO-GENERATED by HighSpeedDAL framework");
                    code.AppendLine($"        /// </summary>");

                    // Add [PrimaryKey] attribute if this is the primary key
                    if (property.IsPrimaryKey)
                    {
                        code.AppendLine($"        [PrimaryKey]");
                    }

                    // Add [Identity] attribute if this is auto-increment
                    if (property.IsAutoIncrement)
                    {
                        code.AppendLine($"        [Identity]");
                    }

                    // Add [Column] attribute if column name differs from property name
                    if (property.ColumnName != property.PropertyName)
                    {
                        if (property.MaxLength.HasValue)
                        {
                            code.AppendLine($"        [Column(Name = \"{property.ColumnName}\", MaxLength = {property.MaxLength.Value})]");
                        }
                        else
                        {
                            code.AppendLine($"        [Column(Name = \"{property.ColumnName}\")]");
                        }
                    }

                    // Property declaration with default value
                    string defaultValue = GetDefaultValue(property);
                    code.AppendLine($"        public {property.PropertyType} {property.PropertyName} {{ get; set; }}{defaultValue}");
                    code.AppendLine();
                }

                    private string GetPropertyDescription(string propertyName)
                    {
                        return propertyName switch
                        {
                            "Id" => "Primary key for this entity. Automatically generated by the database.",
                            "CreatedDate" => "When this record was created. Automatically populated on INSERT.",
                            "CreatedBy" => "Username who created this record. Automatically populated on INSERT.",
                            "ModifiedDate" => "When this record was last modified. Automatically populated on UPDATE.",
                            "ModifiedBy" => "Username who last modified this record. Automatically populated on UPDATE.",
                            "IsDeleted" => "Soft delete flag. Set to true when record is deleted. Automatically populated on DELETE.",
                            "DeletedDate" => "When this record was soft-deleted. Automatically populated on DELETE.",
                            "DeletedBy" => "Username who soft-deleted this record. Automatically populated on DELETE.",
                            _ => $"{propertyName} property."
                        };
                    }

                                    private string GetDefaultValue(PropertyMetadata property)
                                    {
                                        // For non-nullable value types and strings, provide default initializers
                                        // Note: Auto-properties WITHOUT initializers don't need a semicolon
                                        // Auto-properties WITH initializers need the semicolon as part of the initializer
                                        if (!property.IsNullable)
                                        {
                                            if (property.PropertyType == "string")
                                            {
                                                return " = string.Empty;";
                                            }
                                            else if (property.PropertyType == "bool")
                                            {
                                                return " = false;";
                                            }
                                        }

                                        // No initializer - auto-property syntax doesn't need semicolon
                                        return string.Empty;
                                    }

                        /// <summary>
                        /// Generates ShallowClone and DeepClone methods for defensive copying in caches
                        /// </summary>
                        private void GenerateCloneMethodsInternal(StringBuilder code)
                        {
                            // Use ONLY metadata.Properties - missingProperties were already added to it by DalSourceGenerator
                            // DO NOT add _missingProperties again here or we get duplicates in clone initialization
                            List<PropertyMetadata> allProperties = new List<PropertyMetadata>(_metadata.Properties);

                            if (allProperties.Count == 0)
                            {
                                return; // No properties to clone
                            }

                            code.AppendLine();
                            code.AppendLine("        /// <summary>");
                            code.AppendLine("        /// Creates a shallow clone of this entity (for cache defensive copying)");
                            code.AppendLine("        /// </summary>");
                            code.AppendLine($"        public {_metadata.ClassName} ShallowClone()");
                            code.AppendLine("        {");
                            code.AppendLine($"            return new {_metadata.ClassName}");
                            code.AppendLine("            {");

                            // Generate property assignments for shallow clone
                            for (int i = 0; i < allProperties.Count; i++)
                            {
                                PropertyMetadata prop = allProperties[i];
                                if (prop.IsNotMapped)
                                {
                                    continue; // Skip [NotMapped] properties
                                }

                                string comma = i < allProperties.Count - 1 ? "," : string.Empty;
                                code.AppendLine($"                {prop.PropertyName} = this.{prop.PropertyName}{comma}");
                            }

                            code.AppendLine("            };");
                            code.AppendLine("        }");
                            code.AppendLine();

                            // Generate deep clone method
                            code.AppendLine("        /// <summary>");
                            code.AppendLine("        /// Creates a deep clone of this entity (for complex object graphs)");
                            code.AppendLine("        /// Note: For collections, creates new collection with shallow clones of items");
                            code.AppendLine("        /// </summary>");
                            code.AppendLine($"        public {_metadata.ClassName} DeepClone()");
                            code.AppendLine("        {");
                            code.AppendLine($"            return new {_metadata.ClassName}");
                            code.AppendLine("            {");

                            // Generate property assignments for deep clone
                            bool needsLinqUsing = false;
                            for (int i = 0; i < allProperties.Count; i++)
                            {
                                PropertyMetadata prop = allProperties[i];
                                if (prop.IsNotMapped)
                                {
                                    continue; // Skip [NotMapped] properties
                                }

                                string comma = i < allProperties.Count - 1 ? "," : string.Empty;

                                // Deep clone collections (List, IEnumerable, etc.)
                                if (IsCollectionType(prop.PropertyType))
                                {
                                    needsLinqUsing = true;
                                    // For collections, create new collection with shallow clones if possible
                                    code.AppendLine($"                {prop.PropertyName} = this.{prop.PropertyName}?.ToList(){comma}");
                                }
                                else if (IsComplexType(prop.PropertyType))
                                {
                                    // For custom types that might have ShallowClone method
                                    code.AppendLine($"                {prop.PropertyName} = this.{prop.PropertyName}{comma}");
                                }
                                else
                                {
                                    // For simple types (int, string, DateTime, etc.) - direct assignment
                                    code.AppendLine($"                {prop.PropertyName} = this.{prop.PropertyName}{comma}");
                                }
                            }

                            code.AppendLine("            };");
                            code.AppendLine("        }");
                        }

                        /// <summary>
                        /// Determines if a property type is a collection
                        /// </summary>
                        private bool IsCollectionType(string propertyType)
                        {
                            return propertyType.Contains("List<") ||
                                   propertyType.Contains("IEnumerable<") ||
                                   propertyType.Contains("ICollection<") ||
                                   propertyType.Contains("[]");
                        }

                        /// <summary>
                        /// Determines if a property type is a complex type (not primitive/string/DateTime)
                        /// </summary>
                        private bool IsComplexType(string propertyType)
                        {
                            // Simple types that don't need deep cloning
                            string[] simpleTypes = new[]
                            {
                                "int", "long", "short", "byte", "uint", "ulong", "ushort",
                                "float", "double", "decimal", "bool", "char",
                                "string", "DateTime", "DateTimeOffset", "TimeSpan", "Guid",
                                "int?", "long?", "short?", "byte?", "uint?", "ulong?", "ushort?",
                                "float?", "double?", "decimal?", "bool?", "char?",
                                "DateTime?", "DateTimeOffset?", "TimeSpan?", "Guid?"
                            };

                            return !simpleTypes.Contains(propertyType);
                        }
                    }
}
