using System.Text;
using HighSpeedDAL.SourceGenerators.Models;
using Microsoft.CodeAnalysis;

namespace HighSpeedDAL.SourceGenerators.Generation;

/// <summary>
/// Generates audit and soft-delete properties for partial entity classes
/// </summary>
internal sealed class PropertyAutoGenerator
{
    /// <summary>
    /// Generates a partial class with auto-generated properties for entities with [AutoAudit] or [SoftDelete] attributes
    /// </summary>
    public static string GeneratePartialClass(EntityMetadata metadata, INamedTypeSymbol classSymbol)
    {
        if (!metadata.IsAuditable && !metadata.HasSoftDelete)
        {
            return string.Empty; // No properties to generate
        }

        StringBuilder code = new StringBuilder();

        // Add file header
        code.AppendLine("// <auto-generated>");
        code.AppendLine("//     This code was generated by HighSpeedDAL Source Generator.");
        code.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        code.AppendLine("// </auto-generated>");
        code.AppendLine();
        code.AppendLine("#nullable enable");
        code.AppendLine();

        // Add namespace
        string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        code.AppendLine($"namespace {namespaceName};");
        code.AppendLine();

        // Add XML documentation
        code.AppendLine("/// <summary>");
        code.AppendLine($"/// Partial class with auto-generated properties for {metadata.ClassName}");
        code.AppendLine("/// </summary>");

        // Generate partial class declaration
        code.AppendLine($"public partial class {metadata.ClassName}");
        code.AppendLine("{");

        // Generate audit properties if needed
        if (metadata.IsAuditable)
        {
            code.AppendLine("    /// <summary>");
            code.AppendLine("    /// User who created this record (auto-populated by framework)");
            code.AppendLine("    /// </summary>");
            code.AppendLine("    public string CreatedBy { get; set; } = string.Empty;");
            code.AppendLine();

            code.AppendLine("    /// <summary>");
            code.AppendLine("    /// Date and time when this record was created (auto-populated by framework)");
            code.AppendLine("    /// </summary>");
            code.AppendLine("    public DateTime CreatedDate { get; set; }");
            code.AppendLine();

            code.AppendLine("    /// <summary>");
            code.AppendLine("    /// User who last modified this record (auto-populated by framework)");
            code.AppendLine("    /// </summary>");
            code.AppendLine("    public string ModifiedBy { get; set; } = string.Empty;");
            code.AppendLine();

            code.AppendLine("    /// <summary>");
            code.AppendLine("    /// Date and time when this record was last modified (auto-populated by framework)");
            code.AppendLine("    /// </summary>");
            code.AppendLine("    public DateTime ModifiedDate { get; set; }");
        }

        // Generate soft-delete properties if needed
        if (metadata.HasSoftDelete)
        {
            if (metadata.IsAuditable)
            {
                code.AppendLine();
            }

            code.AppendLine("    /// <summary>");
            code.AppendLine("    /// Indicates whether this record is soft-deleted (auto-populated by framework)");
            code.AppendLine("    /// </summary>");
            code.AppendLine("    public bool IsDeleted { get; set; }");
            code.AppendLine();

            code.AppendLine("    /// <summary>");
            code.AppendLine("    /// Date and time when this record was soft-deleted (auto-populated by framework)");
            code.AppendLine("    /// </summary>");
            code.AppendLine("    public DateTime? DeletedDate { get; set; }");
            code.AppendLine();

            code.AppendLine("    /// <summary>");
            code.AppendLine("    /// User who soft-deleted this record (auto-populated by framework)");
            code.AppendLine("    /// </summary>");
            code.AppendLine("    public string? DeletedBy { get; set; }");
        }

        code.AppendLine("}");

        return code.ToString();
    }
}
