using HighSpeedDAL.Core.Attributes;
using HighSpeedDAL.DataManagement;

namespace HighSpeedDAL.FrameworkUsage.Tests.Entities;

/// <summary>
/// Example entity demonstrating soft delete and auto-audit features.
/// Framework auto-generates: CreatedBy, CreatedDate, ModifiedBy, ModifiedDate,
/// IsDeleted, DeletedDate, DeletedBy properties.
/// </summary>
[Table("Orders")]
[Cache(CacheStrategy.Memory, ExpirationSeconds = 600)]
[SoftDelete]
[AutoAudit]
public partial class Order
{
    // Id property auto-generated by framework
    // Audit properties (CreatedBy, CreatedDate, ModifiedBy, ModifiedDate) auto-generated by framework
    // Soft delete properties (IsDeleted, DeletedDate, DeletedBy) auto-generated by framework
    public string OrderNumber { get; set; } = string.Empty;
    public int CustomerId { get; set; }
    public decimal TotalAmount { get; set; }
    public string Status { get; set; } = "Pending";
    public DateTime OrderDate { get; set; }
}
