using HighSpeedDAL.Core.Attributes;

namespace HighSpeedDAL.FrameworkUsage.Tests.Entities;

/// <summary>
/// Example entity demonstrating framework usage with source generation.
/// This is how developers should define entities in their projects.
/// 
/// NOTE: This entity uses source generation - the ProductDal class is automatically
/// generated at compile time.
/// </summary>
[Table("Products")]
[Cache(CacheStrategy.Memory, MaxSize = 1000, ExpirationSeconds = 300)]
public partial class Product
{
    // Id property auto-generated by framework
    public string Name { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public int StockQuantity { get; set; }
    public string Category { get; set; } = string.Empty;
    public DateTime CreatedDate { get; set; }
    public bool IsActive { get; set; } = true;
}
